package com.kakarote.crm9.erp.phone.model;

public class ZhangweiStaff {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zhangwei_staff.sid
     *
     * @mbg.generated Wed Jan 06 16:06:30 CST 2021
     */
    private Integer sid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zhangwei_staff.yname
     *
     * @mbg.generated Wed Jan 06 16:06:30 CST 2021
     */
    private String yname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zhangwei_staff.duty
     *
     * @mbg.generated Wed Jan 06 16:06:30 CST 2021
     */
    private String duty;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zhangwei_staff.telephone
     *
     * @mbg.generated Wed Jan 06 16:06:30 CST 2021
     */
    private String telephone;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zhangwei_staff.sid
     *
     * @return the value of zhangwei_staff.sid
     *
     * @mbg.generated Wed Jan 06 16:06:30 CST 2021
     */
    public Integer getSid() {
        return sid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zhangwei_staff.sid
     *
     * @param sid the value for zhangwei_staff.sid
     *
     * @mbg.generated Wed Jan 06 16:06:30 CST 2021
     */
    public void setSid(Integer sid) {
        this.sid = sid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zhangwei_staff.yname
     *
     * @return the value of zhangwei_staff.yname
     *
     * @mbg.generated Wed Jan 06 16:06:30 CST 2021
     */
    public String getYname() {
        return yname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zhangwei_staff.yname
     *
     * @param yname the value for zhangwei_staff.yname
     *
     * @mbg.generated Wed Jan 06 16:06:30 CST 2021
     */
    public void setYname(String yname) {
        this.yname = yname == null ? null : yname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zhangwei_staff.duty
     *
     * @return the value of zhangwei_staff.duty
     *
     * @mbg.generated Wed Jan 06 16:06:30 CST 2021
     */
    public String getDuty() {
        return duty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zhangwei_staff.duty
     *
     * @param duty the value for zhangwei_staff.duty
     *
     * @mbg.generated Wed Jan 06 16:06:30 CST 2021
     */
    public void setDuty(String duty) {
        this.duty = duty == null ? null : duty.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zhangwei_staff.telephone
     *
     * @return the value of zhangwei_staff.telephone
     *
     * @mbg.generated Wed Jan 06 16:06:30 CST 2021
     */
    public String getTelephone() {
        return telephone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zhangwei_staff.telephone
     *
     * @param telephone the value for zhangwei_staff.telephone
     *
     * @mbg.generated Wed Jan 06 16:06:30 CST 2021
     */
    public void setTelephone(String telephone) {
        this.telephone = telephone == null ? null : telephone.trim();
    }
}