package com.kakarote.crm9.erp.phone.model;

public class ZhangweiSDepartmentKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zhangwei_s_department.sid
     *
     * @mbg.generated Wed Jan 06 16:06:30 CST 2021
     */
    private Integer sid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zhangwei_s_department.did
     *
     * @mbg.generated Wed Jan 06 16:06:30 CST 2021
     */
    private Integer did;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zhangwei_s_department.sid
     *
     * @return the value of zhangwei_s_department.sid
     *
     * @mbg.generated Wed Jan 06 16:06:30 CST 2021
     */
    public Integer getSid() {
        return sid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zhangwei_s_department.sid
     *
     * @param sid the value for zhangwei_s_department.sid
     *
     * @mbg.generated Wed Jan 06 16:06:30 CST 2021
     */
    public void setSid(Integer sid) {
        this.sid = sid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zhangwei_s_department.did
     *
     * @return the value of zhangwei_s_department.did
     *
     * @mbg.generated Wed Jan 06 16:06:30 CST 2021
     */
    public Integer getDid() {
        return did;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zhangwei_s_department.did
     *
     * @param did the value for zhangwei_s_department.did
     *
     * @mbg.generated Wed Jan 06 16:06:30 CST 2021
     */
    public void setDid(Integer did) {
        this.did = did;
    }
}