package com.kakarote.crm9.erp.log.model;

public class Log {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column log.logid
     *
     * @mbg.generated Sat Jan 09 15:29:19 CST 2021
     */
    private Integer logid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column log.username
     *
     * @mbg.generated Sat Jan 09 15:29:19 CST 2021
     */
    private String username;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column log.categoryid
     *
     * @mbg.generated Sat Jan 09 15:29:19 CST 2021
     */
    private Integer categoryid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column log.createid
     *
     * @mbg.generated Sat Jan 09 15:29:19 CST 2021
     */
    private String createid;

    private String today;
    private String tomorrow;
    private String question;

    public String getToday() {
        return today;
    }

    public void setToday(String today) {
        this.today = today;
    }

    public String getTomorrow() {
        return tomorrow;
    }

    public void setTomorrow(String tomorrow) {
        this.tomorrow = tomorrow;
    }

    public String getQuestion() {
        return question;
    }

    public void setQuestion(String question) {
        this.question = question;
    }

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column log.data
     *
     * @mbg.generated Sat Jan 09 15:29:19 CST 2021
     */
    private String data;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column log.picture
     *
     * @mbg.generated Sat Jan 09 15:29:19 CST 2021
     */
    private String picture;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column log.name
     *
     * @mbg.generated Sat Jan 09 15:29:19 CST 2021
     */
    private String name;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column log.logid
     *
     * @return the value of log.logid
     *
     * @mbg.generated Sat Jan 09 15:29:19 CST 2021
     */
    public Integer getLogid() {
        return logid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column log.logid
     *
     * @param logid the value for log.logid
     *
     * @mbg.generated Sat Jan 09 15:29:19 CST 2021
     */
    public void setLogid(Integer logid) {
        this.logid = logid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column log.username
     *
     * @return the value of log.username
     *
     * @mbg.generated Sat Jan 09 15:29:19 CST 2021
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column log.username
     *
     * @param username the value for log.username
     *
     * @mbg.generated Sat Jan 09 15:29:19 CST 2021
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column log.categoryid
     *
     * @return the value of log.categoryid
     *
     * @mbg.generated Sat Jan 09 15:29:19 CST 2021
     */
    public Integer getCategoryid() {
        return categoryid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column log.categoryid
     *
     * @param categoryid the value for log.categoryid
     *
     * @mbg.generated Sat Jan 09 15:29:19 CST 2021
     */
    public void setCategoryid(Integer categoryid) {
        this.categoryid = categoryid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column log.createid
     *
     * @return the value of log.createid
     *
     * @mbg.generated Sat Jan 09 15:29:19 CST 2021
     */
    public String getCreateid() {
        return createid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column log.createid
     *
     * @param createid the value for log.createid
     *
     * @mbg.generated Sat Jan 09 15:29:19 CST 2021
     */
    public void setCreateid(String createid) {
        this.createid = createid == null ? null : createid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column log.data
     *
     * @return the value of log.data
     *
     * @mbg.generated Sat Jan 09 15:29:19 CST 2021
     */
    public String getData() {
        return data;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column log.data
     *
     * @param data the value for log.data
     *
     * @mbg.generated Sat Jan 09 15:29:19 CST 2021
     */
    public void setData(String data) {
        this.data = data == null ? null : data.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column log.picture
     *
     * @return the value of log.picture
     *
     * @mbg.generated Sat Jan 09 15:29:19 CST 2021
     */
    public String getPicture() {
        return picture;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column log.picture
     *
     * @param picture the value for log.picture
     *
     * @mbg.generated Sat Jan 09 15:29:19 CST 2021
     */
    public void setPicture(String picture) {
        this.picture = picture == null ? null : picture.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column log.name
     *
     * @return the value of log.name
     *
     * @mbg.generated Sat Jan 09 15:29:19 CST 2021
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column log.name
     *
     * @param name the value for log.name
     *
     * @mbg.generated Sat Jan 09 15:29:19 CST 2021
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }
}