package com.kakarote.crm9.erp.phone.dao;

import com.kakarote.crm9.erp.phone.model.ZhangweiSDepartmentExample;
import com.kakarote.crm9.erp.phone.model.ZhangweiSDepartmentKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ZhangweiSDepartmentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zhangwei_s_department
     *
     * @mbg.generated Wed Jan 06 16:06:30 CST 2021
     */
    long countByExample(ZhangweiSDepartmentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zhangwei_s_department
     *
     * @mbg.generated Wed Jan 06 16:06:30 CST 2021
     */
    int deleteByExample(ZhangweiSDepartmentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zhangwei_s_department
     *
     * @mbg.generated Wed Jan 06 16:06:30 CST 2021
     */
    int deleteByPrimaryKey(ZhangweiSDepartmentKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zhangwei_s_department
     *
     * @mbg.generated Wed Jan 06 16:06:30 CST 2021
     */
    int insert(ZhangweiSDepartmentKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zhangwei_s_department
     *
     * @mbg.generated Wed Jan 06 16:06:30 CST 2021
     */
    int insertSelective(ZhangweiSDepartmentKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zhangwei_s_department
     *
     * @mbg.generated Wed Jan 06 16:06:30 CST 2021
     */
    List<ZhangweiSDepartmentKey> selectByExample(ZhangweiSDepartmentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zhangwei_s_department
     *
     * @mbg.generated Wed Jan 06 16:06:30 CST 2021
     */
    int updateByExampleSelective(@Param("record") ZhangweiSDepartmentKey record, @Param("example") ZhangweiSDepartmentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zhangwei_s_department
     *
     * @mbg.generated Wed Jan 06 16:06:30 CST 2021
     */
    int updateByExample(@Param("record") ZhangweiSDepartmentKey record, @Param("example") ZhangweiSDepartmentExample example);
}