package com.kakarote.crm9.erp.phone.dao;

import com.kakarote.crm9.erp.phone.model.ZhangweiDepartment;
import com.kakarote.crm9.erp.phone.model.ZhangweiDepartmentExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ZhangweiDepartmentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zhangwei_department
     *
     * @mbg.generated Wed Jan 06 16:06:30 CST 2021
     */
    long countByExample(ZhangweiDepartmentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zhangwei_department
     *
     * @mbg.generated Wed Jan 06 16:06:30 CST 2021
     */
    int deleteByExample(ZhangweiDepartmentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zhangwei_department
     *
     * @mbg.generated Wed Jan 06 16:06:30 CST 2021
     */
    int deleteByPrimaryKey(Integer did);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zhangwei_department
     *
     * @mbg.generated Wed Jan 06 16:06:30 CST 2021
     */
    int insert(ZhangweiDepartment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zhangwei_department
     *
     * @mbg.generated Wed Jan 06 16:06:30 CST 2021
     */
    int insertSelective(ZhangweiDepartment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zhangwei_department
     *
     * @mbg.generated Wed Jan 06 16:06:30 CST 2021
     */
    List<ZhangweiDepartment> selectByExample(ZhangweiDepartmentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zhangwei_department
     *
     * @mbg.generated Wed Jan 06 16:06:30 CST 2021
     */
    ZhangweiDepartment selectByPrimaryKey(Integer did);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zhangwei_department
     *
     * @mbg.generated Wed Jan 06 16:06:30 CST 2021
     */
    int updateByExampleSelective(@Param("record") ZhangweiDepartment record, @Param("example") ZhangweiDepartmentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zhangwei_department
     *
     * @mbg.generated Wed Jan 06 16:06:30 CST 2021
     */
    int updateByExample(@Param("record") ZhangweiDepartment record, @Param("example") ZhangweiDepartmentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zhangwei_department
     *
     * @mbg.generated Wed Jan 06 16:06:30 CST 2021
     */
    int updateByPrimaryKeySelective(ZhangweiDepartment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zhangwei_department
     *
     * @mbg.generated Wed Jan 06 16:06:30 CST 2021
     */
    int updateByPrimaryKey(ZhangweiDepartment record);
}