package com.kakarote.crm9.erp.phone.dao;

import com.kakarote.crm9.erp.phone.model.ZhangweiStaff;
import com.kakarote.crm9.erp.phone.model.ZhangweiStaffExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ZhangweiStaffMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zhangwei_staff
     *
     * @mbg.generated Wed Jan 06 16:06:30 CST 2021
     */
    long countByExample(ZhangweiStaffExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zhangwei_staff
     *
     * @mbg.generated Wed Jan 06 16:06:30 CST 2021
     */
    int deleteByExample(ZhangweiStaffExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zhangwei_staff
     *
     * @mbg.generated Wed Jan 06 16:06:30 CST 2021
     */
    int deleteByPrimaryKey(Integer sid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zhangwei_staff
     *
     * @mbg.generated Wed Jan 06 16:06:30 CST 2021
     */
    int insert(ZhangweiStaff record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zhangwei_staff
     *
     * @mbg.generated Wed Jan 06 16:06:30 CST 2021
     */
    int insertSelective(ZhangweiStaff record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zhangwei_staff
     *
     * @mbg.generated Wed Jan 06 16:06:30 CST 2021
     */
    List<ZhangweiStaff> selectByExample(ZhangweiStaffExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zhangwei_staff
     *
     * @mbg.generated Wed Jan 06 16:06:30 CST 2021
     */
    ZhangweiStaff selectByPrimaryKey(Integer sid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zhangwei_staff
     *
     * @mbg.generated Wed Jan 06 16:06:30 CST 2021
     */
    int updateByExampleSelective(@Param("record") ZhangweiStaff record, @Param("example") ZhangweiStaffExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zhangwei_staff
     *
     * @mbg.generated Wed Jan 06 16:06:30 CST 2021
     */
    int updateByExample(@Param("record") ZhangweiStaff record, @Param("example") ZhangweiStaffExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zhangwei_staff
     *
     * @mbg.generated Wed Jan 06 16:06:30 CST 2021
     */
    int updateByPrimaryKeySelective(ZhangweiStaff record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zhangwei_staff
     *
     * @mbg.generated Wed Jan 06 16:06:30 CST 2021
     */
    int updateByPrimaryKey(ZhangweiStaff record);
}