package com.kakarote.crm9.erp.approval.model;

public class CustomerTaskKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer_task.cid
     *
     * @mbg.generated Tue Jan 05 16:20:55 CST 2021
     */
    private Integer cid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer_task.tid
     *
     * @mbg.generated Tue Jan 05 16:20:55 CST 2021
     */
    private Integer tid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer_task.cid
     *
     * @return the value of customer_task.cid
     *
     * @mbg.generated Tue Jan 05 16:20:55 CST 2021
     */
    public Integer getCid() {
        return cid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer_task.cid
     *
     * @param cid the value for customer_task.cid
     *
     * @mbg.generated Tue Jan 05 16:20:55 CST 2021
     */
    public void setCid(Integer cid) {
        this.cid = cid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer_task.tid
     *
     * @return the value of customer_task.tid
     *
     * @mbg.generated Tue Jan 05 16:20:55 CST 2021
     */
    public Integer getTid() {
        return tid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer_task.tid
     *
     * @param tid the value for customer_task.tid
     *
     * @mbg.generated Tue Jan 05 16:20:55 CST 2021
     */
    public void setTid(Integer tid) {
        this.tid = tid;
    }
}