package com.kakarote.crm9.erp.approval.model;

public class LoginUser {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column login_user.id
     *
     * @mbg.generated Wed Jan 06 16:46:44 CST 2021
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column login_user.name
     *
     * @mbg.generated Wed Jan 06 16:46:44 CST 2021
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column login_user.username
     *
     * @mbg.generated Wed Jan 06 16:46:44 CST 2021
     */
    private String username;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column login_user.pwd
     *
     * @mbg.generated Wed Jan 06 16:46:44 CST 2021
     */
    private String pwd;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column login_user.id
     *
     * @return the value of login_user.id
     *
     * @mbg.generated Wed Jan 06 16:46:44 CST 2021
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column login_user.id
     *
     * @param id the value for login_user.id
     *
     * @mbg.generated Wed Jan 06 16:46:44 CST 2021
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column login_user.name
     *
     * @return the value of login_user.name
     *
     * @mbg.generated Wed Jan 06 16:46:44 CST 2021
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column login_user.name
     *
     * @param name the value for login_user.name
     *
     * @mbg.generated Wed Jan 06 16:46:44 CST 2021
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column login_user.username
     *
     * @return the value of login_user.username
     *
     * @mbg.generated Wed Jan 06 16:46:44 CST 2021
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column login_user.username
     *
     * @param username the value for login_user.username
     *
     * @mbg.generated Wed Jan 06 16:46:44 CST 2021
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column login_user.pwd
     *
     * @return the value of login_user.pwd
     *
     * @mbg.generated Wed Jan 06 16:46:44 CST 2021
     */
    public String getPwd() {
        return pwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column login_user.pwd
     *
     * @param pwd the value for login_user.pwd
     *
     * @mbg.generated Wed Jan 06 16:46:44 CST 2021
     */
    public void setPwd(String pwd) {
        this.pwd = pwd == null ? null : pwd.trim();
    }
}