package com.kakarote.crm9.erp.approval.model;

public class SqPriority {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sq_priority.id
     *
     * @mbg.generated Wed Jan 06 16:46:44 CST 2021
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sq_priority.type
     *
     * @mbg.generated Wed Jan 06 16:46:44 CST 2021
     */
    private String type;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sq_priority.id
     *
     * @return the value of sq_priority.id
     *
     * @mbg.generated Wed Jan 06 16:46:44 CST 2021
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sq_priority.id
     *
     * @param id the value for sq_priority.id
     *
     * @mbg.generated Wed Jan 06 16:46:44 CST 2021
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sq_priority.type
     *
     * @return the value of sq_priority.type
     *
     * @mbg.generated Wed Jan 06 16:46:44 CST 2021
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sq_priority.type
     *
     * @param type the value for sq_priority.type
     *
     * @mbg.generated Wed Jan 06 16:46:44 CST 2021
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }
}