package com.kakarote.crm9.erp.approval.model;

public class SqTask {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sq_task.id
     *
     * @mbg.generated Wed Jan 06 16:46:44 CST 2021
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sq_task.name
     *
     * @mbg.generated Wed Jan 06 16:46:44 CST 2021
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sq_task.type
     *
     * @mbg.generated Wed Jan 06 16:46:44 CST 2021
     */
    private String type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sq_task.status
     *
     * @mbg.generated Wed Jan 06 16:46:44 CST 2021
     */
    private String status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sq_task.prId
     *
     * @mbg.generated Wed Jan 06 16:46:44 CST 2021
     */
    private Integer prid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sq_task.time
     *
     * @mbg.generated Wed Jan 06 16:46:44 CST 2021
     */
    private String time;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sq_task.id
     *
     * @return the value of sq_task.id
     *
     * @mbg.generated Wed Jan 06 16:46:44 CST 2021
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sq_task.id
     *
     * @param id the value for sq_task.id
     *
     * @mbg.generated Wed Jan 06 16:46:44 CST 2021
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sq_task.name
     *
     * @return the value of sq_task.name
     *
     * @mbg.generated Wed Jan 06 16:46:44 CST 2021
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sq_task.name
     *
     * @param name the value for sq_task.name
     *
     * @mbg.generated Wed Jan 06 16:46:44 CST 2021
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sq_task.type
     *
     * @return the value of sq_task.type
     *
     * @mbg.generated Wed Jan 06 16:46:44 CST 2021
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sq_task.type
     *
     * @param type the value for sq_task.type
     *
     * @mbg.generated Wed Jan 06 16:46:44 CST 2021
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sq_task.status
     *
     * @return the value of sq_task.status
     *
     * @mbg.generated Wed Jan 06 16:46:44 CST 2021
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sq_task.status
     *
     * @param status the value for sq_task.status
     *
     * @mbg.generated Wed Jan 06 16:46:44 CST 2021
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sq_task.prId
     *
     * @return the value of sq_task.prId
     *
     * @mbg.generated Wed Jan 06 16:46:44 CST 2021
     */
    public Integer getPrid() {
        return prid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sq_task.prId
     *
     * @param prid the value for sq_task.prId
     *
     * @mbg.generated Wed Jan 06 16:46:44 CST 2021
     */
    public void setPrid(Integer prid) {
        this.prid = prid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sq_task.time
     *
     * @return the value of sq_task.time
     *
     * @mbg.generated Wed Jan 06 16:46:44 CST 2021
     */
    public String getTime() {
        return time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sq_task.time
     *
     * @param time the value for sq_task.time
     *
     * @mbg.generated Wed Jan 06 16:46:44 CST 2021
     */
    public void setTime(String time) {
        this.time = time == null ? null : time.trim();
    }
}