package com.kakarote.crm9.erp.approval.model;

public class SqUserTaskKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sq_user_task.id
     *
     * @mbg.generated Thu Jan 07 15:54:59 CST 2021
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sq_user_task.tid
     *
     * @mbg.generated Thu Jan 07 15:54:59 CST 2021
     */
    private Integer tid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sq_user_task.id
     *
     * @return the value of sq_user_task.id
     *
     * @mbg.generated Thu Jan 07 15:54:59 CST 2021
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sq_user_task.id
     *
     * @param id the value for sq_user_task.id
     *
     * @mbg.generated Thu Jan 07 15:54:59 CST 2021
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sq_user_task.tid
     *
     * @return the value of sq_user_task.tid
     *
     * @mbg.generated Thu Jan 07 15:54:59 CST 2021
     */
    public Integer getTid() {
        return tid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sq_user_task.tid
     *
     * @param tid the value for sq_user_task.tid
     *
     * @mbg.generated Thu Jan 07 15:54:59 CST 2021
     */
    public void setTid(Integer tid) {
        this.tid = tid;
    }
}