package com.kakarote.crm9.erp.approval.model;

public class SqUserUserKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sq_user_user.uid
     *
     * @mbg.generated Thu Jan 07 15:54:59 CST 2021
     */
    private Integer uid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sq_user_user.cid
     *
     * @mbg.generated Thu Jan 07 15:54:59 CST 2021
     */
    private Integer cid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sq_user_user.uid
     *
     * @return the value of sq_user_user.uid
     *
     * @mbg.generated Thu Jan 07 15:54:59 CST 2021
     */
    public Integer getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sq_user_user.uid
     *
     * @param uid the value for sq_user_user.uid
     *
     * @mbg.generated Thu Jan 07 15:54:59 CST 2021
     */
    public void setUid(Integer uid) {
        this.uid = uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sq_user_user.cid
     *
     * @return the value of sq_user_user.cid
     *
     * @mbg.generated Thu Jan 07 15:54:59 CST 2021
     */
    public Integer getCid() {
        return cid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sq_user_user.cid
     *
     * @param cid the value for sq_user_user.cid
     *
     * @mbg.generated Thu Jan 07 15:54:59 CST 2021
     */
    public void setCid(Integer cid) {
        this.cid = cid;
    }
}