package com.kakarote.crm9.erp.approval.model;

public class SqUserTaskKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sq_user_task.uid
     *
     * @mbg.generated Wed Jan 06 16:46:44 CST 2021
     */
    private Integer uid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sq_user_task.tid
     *
     * @mbg.generated Wed Jan 06 16:46:44 CST 2021
     */
    private Integer tid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sq_user_task.uid
     *
     * @return the value of sq_user_task.uid
     *
     * @mbg.generated Wed Jan 06 16:46:44 CST 2021
     */
    public Integer getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sq_user_task.uid
     *
     * @param uid the value for sq_user_task.uid
     *
     * @mbg.generated Wed Jan 06 16:46:44 CST 2021
     */
    public void setUid(Integer uid) {
        this.uid = uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sq_user_task.tid
     *
     * @return the value of sq_user_task.tid
     *
     * @mbg.generated Wed Jan 06 16:46:44 CST 2021
     */
    public Integer getTid() {
        return tid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sq_user_task.tid
     *
     * @param tid the value for sq_user_task.tid
     *
     * @mbg.generated Wed Jan 06 16:46:44 CST 2021
     */
    public void setTid(Integer tid) {
        this.tid = tid;
    }
}