package com.kakarote.crm9.erp.approval.model;

public class Task {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task.id
     *
     * @mbg.generated Tue Jan 05 16:20:55 CST 2021
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task.name
     *
     * @mbg.generated Tue Jan 05 16:20:55 CST 2021
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task.type
     *
     * @mbg.generated Tue Jan 05 16:20:55 CST 2021
     */
    private String type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task.status
     *
     * @mbg.generated Tue Jan 05 16:20:55 CST 2021
     */
    private String status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task.priority
     *
     * @mbg.generated Tue Jan 05 16:20:55 CST 2021
     */
    private Integer priority;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task.time
     *
     * @mbg.generated Tue Jan 05 16:20:55 CST 2021
     */
    private String time;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task.id
     *
     * @return the value of task.id
     *
     * @mbg.generated Tue Jan 05 16:20:55 CST 2021
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task.id
     *
     * @param id the value for task.id
     *
     * @mbg.generated Tue Jan 05 16:20:55 CST 2021
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task.name
     *
     * @return the value of task.name
     *
     * @mbg.generated Tue Jan 05 16:20:55 CST 2021
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task.name
     *
     * @param name the value for task.name
     *
     * @mbg.generated Tue Jan 05 16:20:55 CST 2021
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task.type
     *
     * @return the value of task.type
     *
     * @mbg.generated Tue Jan 05 16:20:55 CST 2021
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task.type
     *
     * @param type the value for task.type
     *
     * @mbg.generated Tue Jan 05 16:20:55 CST 2021
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task.status
     *
     * @return the value of task.status
     *
     * @mbg.generated Tue Jan 05 16:20:55 CST 2021
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task.status
     *
     * @param status the value for task.status
     *
     * @mbg.generated Tue Jan 05 16:20:55 CST 2021
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task.priority
     *
     * @return the value of task.priority
     *
     * @mbg.generated Tue Jan 05 16:20:55 CST 2021
     */
    public Integer getPriority() {
        return priority;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task.priority
     *
     * @param priority the value for task.priority
     *
     * @mbg.generated Tue Jan 05 16:20:55 CST 2021
     */
    public void setPriority(Integer priority) {
        this.priority = priority;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task.time
     *
     * @return the value of task.time
     *
     * @mbg.generated Tue Jan 05 16:20:55 CST 2021
     */
    public String getTime() {
        return time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task.time
     *
     * @param time the value for task.time
     *
     * @mbg.generated Tue Jan 05 16:20:55 CST 2021
     */
    public void setTime(String time) {
        this.time = time == null ? null : time.trim();
    }
}