package com.kakarote.crm9.erp.approval.model;

public class UserTaskKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_task.uid
     *
     * @mbg.generated Tue Jan 05 16:05:38 CST 2021
     */
    private Integer uid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_task.tid
     *
     * @mbg.generated Tue Jan 05 16:05:38 CST 2021
     */
    private Integer tid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_task.uid
     *
     * @return the value of user_task.uid
     *
     * @mbg.generated Tue Jan 05 16:05:38 CST 2021
     */
    public Integer getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_task.uid
     *
     * @param uid the value for user_task.uid
     *
     * @mbg.generated Tue Jan 05 16:05:38 CST 2021
     */
    public void setUid(Integer uid) {
        this.uid = uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_task.tid
     *
     * @return the value of user_task.tid
     *
     * @mbg.generated Tue Jan 05 16:05:38 CST 2021
     */
    public Integer getTid() {
        return tid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_task.tid
     *
     * @param tid the value for user_task.tid
     *
     * @mbg.generated Tue Jan 05 16:05:38 CST 2021
     */
    public void setTid(Integer tid) {
        this.tid = tid;
    }
}