package com.kakarote.crm9.erp.approval.model;

public class UserCustomerKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_customer.uid
     *
     * @mbg.generated Tue Jan 05 16:05:38 CST 2021
     */
    private Integer uid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_customer.cid
     *
     * @mbg.generated Tue Jan 05 16:05:38 CST 2021
     */
    private Integer cid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_customer.uid
     *
     * @return the value of user_customer.uid
     *
     * @mbg.generated Tue Jan 05 16:05:38 CST 2021
     */
    public Integer getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_customer.uid
     *
     * @param uid the value for user_customer.uid
     *
     * @mbg.generated Tue Jan 05 16:05:38 CST 2021
     */
    public void setUid(Integer uid) {
        this.uid = uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_customer.cid
     *
     * @return the value of user_customer.cid
     *
     * @mbg.generated Tue Jan 05 16:05:38 CST 2021
     */
    public Integer getCid() {
        return cid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_customer.cid
     *
     * @param cid the value for user_customer.cid
     *
     * @mbg.generated Tue Jan 05 16:05:38 CST 2021
     */
    public void setCid(Integer cid) {
        this.cid = cid;
    }
}