package com.kakarote.crm9.erp.approval.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface UserTaskMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_task
     *
     * @mbg.generated Tue Jan 05 16:05:38 CST 2021
     */
    long countByExample(UserTaskExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_task
     *
     * @mbg.generated Tue Jan 05 16:05:38 CST 2021
     */
    int deleteByExample(UserTaskExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_task
     *
     * @mbg.generated Tue Jan 05 16:05:38 CST 2021
     */
    int deleteByPrimaryKey(UserTaskKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_task
     *
     * @mbg.generated Tue Jan 05 16:05:38 CST 2021
     */
    int insert(UserTaskKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_task
     *
     * @mbg.generated Tue Jan 05 16:05:38 CST 2021
     */
    int insertSelective(UserTaskKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_task
     *
     * @mbg.generated Tue Jan 05 16:05:38 CST 2021
     */
    List<UserTaskKey> selectByExample(UserTaskExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_task
     *
     * @mbg.generated Tue Jan 05 16:05:38 CST 2021
     */
    int updateByExampleSelective(@Param("record") UserTaskKey record, @Param("example") UserTaskExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_task
     *
     * @mbg.generated Tue Jan 05 16:05:38 CST 2021
     */
    int updateByExample(@Param("record") UserTaskKey record, @Param("example") UserTaskExample example);
}