package com.kakarote.crm9.erp.busniess.dao;

import com.kakarote.crm9.erp.busniess.model.BusinessProduct;
import com.kakarote.crm9.erp.busniess.model.BusinessProductExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface BusinessProductMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table business_product
     *
     * @mbg.generated Thu Jan 07 02:25:16 CST 2021
     */
    long countByExample(BusinessProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table business_product
     *
     * @mbg.generated Thu Jan 07 02:25:16 CST 2021
     */
    int deleteByExample(BusinessProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table business_product
     *
     * @mbg.generated Thu Jan 07 02:25:16 CST 2021
     */
    int deleteByPrimaryKey(Integer rId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table business_product
     *
     * @mbg.generated Thu Jan 07 02:25:16 CST 2021
     */
    int insert(BusinessProduct record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table business_product
     *
     * @mbg.generated Thu Jan 07 02:25:16 CST 2021
     */
    int insertSelective(BusinessProduct record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table business_product
     *
     * @mbg.generated Thu Jan 07 02:25:16 CST 2021
     */
    List<BusinessProduct> selectByExample(BusinessProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table business_product
     *
     * @mbg.generated Thu Jan 07 02:25:16 CST 2021
     */
    BusinessProduct selectByPrimaryKey(Integer rId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table business_product
     *
     * @mbg.generated Thu Jan 07 02:25:16 CST 2021
     */
    int updateByExampleSelective(@Param("record") BusinessProduct record, @Param("example") BusinessProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table business_product
     *
     * @mbg.generated Thu Jan 07 02:25:16 CST 2021
     */
    int updateByExample(@Param("record") BusinessProduct record, @Param("example") BusinessProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table business_product
     *
     * @mbg.generated Thu Jan 07 02:25:16 CST 2021
     */
    int updateByPrimaryKeySelective(BusinessProduct record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table business_product
     *
     * @mbg.generated Thu Jan 07 02:25:16 CST 2021
     */
    int updateByPrimaryKey(BusinessProduct record);
}