package com.kakarote.crm9.erp.busniess.dao;

import com.kakarote.crm9.erp.busniess.model.BusinessStatus;
import com.kakarote.crm9.erp.busniess.model.BusinessStatusExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface BusinessStatusMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table business_status
     *
     * @mbg.generated Fri Jan 08 15:35:19 CST 2021
     */
    long countByExample(BusinessStatusExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table business_status
     *
     * @mbg.generated Fri Jan 08 15:35:19 CST 2021
     */
    int deleteByExample(BusinessStatusExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table business_status
     *
     * @mbg.generated Fri Jan 08 15:35:19 CST 2021
     */
    int deleteByPrimaryKey(Integer sid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table business_status
     *
     * @mbg.generated Fri Jan 08 15:35:19 CST 2021
     */
    int insert(BusinessStatus record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table business_status
     *
     * @mbg.generated Fri Jan 08 15:35:19 CST 2021
     */
    int insertSelective(BusinessStatus record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table business_status
     *
     * @mbg.generated Fri Jan 08 15:35:19 CST 2021
     */
    List<BusinessStatus> selectByExample(BusinessStatusExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table business_status
     *
     * @mbg.generated Fri Jan 08 15:35:19 CST 2021
     */
    BusinessStatus selectByPrimaryKey(Integer sid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table business_status
     *
     * @mbg.generated Fri Jan 08 15:35:19 CST 2021
     */
    int updateByExampleSelective(@Param("record") BusinessStatus record, @Param("example") BusinessStatusExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table business_status
     *
     * @mbg.generated Fri Jan 08 15:35:19 CST 2021
     */
    int updateByExample(@Param("record") BusinessStatus record, @Param("example") BusinessStatusExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table business_status
     *
     * @mbg.generated Fri Jan 08 15:35:19 CST 2021
     */
    int updateByPrimaryKeySelective(BusinessStatus record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table business_status
     *
     * @mbg.generated Fri Jan 08 15:35:19 CST 2021
     */
    int updateByPrimaryKey(BusinessStatus record);
}