package com.kakarote.crm9.erp.busniess.dao;

import com.kakarote.crm9.erp.busniess.model.BusinessType;
import com.kakarote.crm9.erp.busniess.model.BusinessTypeExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface BusinessTypeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table business_type
     *
     * @mbg.generated Thu Jan 07 02:25:16 CST 2021
     */
    long countByExample(BusinessTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table business_type
     *
     * @mbg.generated Thu Jan 07 02:25:16 CST 2021
     */
    int deleteByExample(BusinessTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table business_type
     *
     * @mbg.generated Thu Jan 07 02:25:16 CST 2021
     */
    int deleteByPrimaryKey(Integer tid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table business_type
     *
     * @mbg.generated Thu Jan 07 02:25:16 CST 2021
     */
    int insert(BusinessType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table business_type
     *
     * @mbg.generated Thu Jan 07 02:25:16 CST 2021
     */
    int insertSelective(BusinessType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table business_type
     *
     * @mbg.generated Thu Jan 07 02:25:16 CST 2021
     */
    List<BusinessType> selectByExample(BusinessTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table business_type
     *
     * @mbg.generated Thu Jan 07 02:25:16 CST 2021
     */
    BusinessType selectByPrimaryKey(Integer tid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table business_type
     *
     * @mbg.generated Thu Jan 07 02:25:16 CST 2021
     */
    int updateByExampleSelective(@Param("record") BusinessType record, @Param("example") BusinessTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table business_type
     *
     * @mbg.generated Thu Jan 07 02:25:16 CST 2021
     */
    int updateByExample(@Param("record") BusinessType record, @Param("example") BusinessTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table business_type
     *
     * @mbg.generated Thu Jan 07 02:25:16 CST 2021
     */
    int updateByPrimaryKeySelective(BusinessType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table business_type
     *
     * @mbg.generated Thu Jan 07 02:25:16 CST 2021
     */
    int updateByPrimaryKey(BusinessType record);
}