package com.kakarote.crm9.erp.busniess.dao;

import com.kakarote.crm9.erp.busniess.model.BusinessChange;
import com.kakarote.crm9.erp.busniess.model.BusinessChangeExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface BusinessChangeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table business_change
     *
     * @mbg.generated Wed Jan 06 17:15:07 CST 2021
     */
    long countByExample(BusinessChangeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table business_change
     *
     * @mbg.generated Wed Jan 06 17:15:07 CST 2021
     */
    int deleteByExample(BusinessChangeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table business_change
     *
     * @mbg.generated Wed Jan 06 17:15:07 CST 2021
     */
    int deleteByPrimaryKey(Integer changeId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table business_change
     *
     * @mbg.generated Wed Jan 06 17:15:07 CST 2021
     */
    int insert(BusinessChange record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table business_change
     *
     * @mbg.generated Wed Jan 06 17:15:07 CST 2021
     */
    int insertSelective(BusinessChange record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table business_change
     *
     * @mbg.generated Wed Jan 06 17:15:07 CST 2021
     */
    List<BusinessChange> selectByExample(BusinessChangeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table business_change
     *
     * @mbg.generated Wed Jan 06 17:15:07 CST 2021
     */
    BusinessChange selectByPrimaryKey(Integer changeId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table business_change
     *
     * @mbg.generated Wed Jan 06 17:15:07 CST 2021
     */
    int updateByExampleSelective(@Param("record") BusinessChange record, @Param("example") BusinessChangeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table business_change
     *
     * @mbg.generated Wed Jan 06 17:15:07 CST 2021
     */
    int updateByExample(@Param("record") BusinessChange record, @Param("example") BusinessChangeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table business_change
     *
     * @mbg.generated Wed Jan 06 17:15:07 CST 2021
     */
    int updateByPrimaryKeySelective(BusinessChange record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table business_change
     *
     * @mbg.generated Wed Jan 06 17:15:07 CST 2021
     */
    int updateByPrimaryKey(BusinessChange record);
}