package com.kakarote.crm9.erp.approval.dao;

import com.kakarote.crm9.erp.approval.model.CustomerTaskExample;
import com.kakarote.crm9.erp.approval.model.CustomerTaskKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CustomerTaskMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer_task
     *
     * @mbg.generated Tue Jan 05 16:20:55 CST 2021
     */
    long countByExample(CustomerTaskExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer_task
     *
     * @mbg.generated Tue Jan 05 16:20:55 CST 2021
     */
    int deleteByExample(CustomerTaskExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer_task
     *
     * @mbg.generated Tue Jan 05 16:20:55 CST 2021
     */
    int deleteByPrimaryKey(CustomerTaskKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer_task
     *
     * @mbg.generated Tue Jan 05 16:20:55 CST 2021
     */
    int insert(CustomerTaskKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer_task
     *
     * @mbg.generated Tue Jan 05 16:20:55 CST 2021
     */
    int insertSelective(CustomerTaskKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer_task
     *
     * @mbg.generated Tue Jan 05 16:20:55 CST 2021
     */
    List<CustomerTaskKey> selectByExample(CustomerTaskExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer_task
     *
     * @mbg.generated Tue Jan 05 16:20:55 CST 2021
     */
    int updateByExampleSelective(@Param("record") CustomerTaskKey record, @Param("example") CustomerTaskExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer_task
     *
     * @mbg.generated Tue Jan 05 16:20:55 CST 2021
     */
    int updateByExample(@Param("record") CustomerTaskKey record, @Param("example") CustomerTaskExample example);
}