package com.kakarote.crm9.erp.approval.dao;

import com.kakarote.crm9.erp.approval.model.LoginUser;
import com.kakarote.crm9.erp.approval.model.LoginUserExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface LoginUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table login_user
     *
     * @mbg.generated Wed Jan 06 16:46:44 CST 2021
     */
    long countByExample(LoginUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table login_user
     *
     * @mbg.generated Wed Jan 06 16:46:44 CST 2021
     */
    int deleteByExample(LoginUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table login_user
     *
     * @mbg.generated Wed Jan 06 16:46:44 CST 2021
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table login_user
     *
     * @mbg.generated Wed Jan 06 16:46:44 CST 2021
     */
    int insert(LoginUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table login_user
     *
     * @mbg.generated Wed Jan 06 16:46:44 CST 2021
     */
    int insertSelective(LoginUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table login_user
     *
     * @mbg.generated Wed Jan 06 16:46:44 CST 2021
     */
    List<LoginUser> selectByExample(LoginUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table login_user
     *
     * @mbg.generated Wed Jan 06 16:46:44 CST 2021
     */
    LoginUser selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table login_user
     *
     * @mbg.generated Wed Jan 06 16:46:44 CST 2021
     */
    int updateByExampleSelective(@Param("record") LoginUser record, @Param("example") LoginUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table login_user
     *
     * @mbg.generated Wed Jan 06 16:46:44 CST 2021
     */
    int updateByExample(@Param("record") LoginUser record, @Param("example") LoginUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table login_user
     *
     * @mbg.generated Wed Jan 06 16:46:44 CST 2021
     */
    int updateByPrimaryKeySelective(LoginUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table login_user
     *
     * @mbg.generated Wed Jan 06 16:46:44 CST 2021
     */
    int updateByPrimaryKey(LoginUser record);

    LoginUser selectByUser(LoginUser user);
}