package com.kakarote.crm9.erp.approval.dao;

import com.kakarote.crm9.erp.approval.model.SqPriority;
import com.kakarote.crm9.erp.approval.model.SqPriorityExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SqPriorityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sq_priority
     *
     * @mbg.generated Wed Jan 06 16:46:44 CST 2021
     */
    long countByExample(SqPriorityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sq_priority
     *
     * @mbg.generated Wed Jan 06 16:46:44 CST 2021
     */
    int deleteByExample(SqPriorityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sq_priority
     *
     * @mbg.generated Wed Jan 06 16:46:44 CST 2021
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sq_priority
     *
     * @mbg.generated Wed Jan 06 16:46:44 CST 2021
     */
    int insert(SqPriority record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sq_priority
     *
     * @mbg.generated Wed Jan 06 16:46:44 CST 2021
     */
    int insertSelective(SqPriority record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sq_priority
     *
     * @mbg.generated Wed Jan 06 16:46:44 CST 2021
     */
    List<SqPriority> selectByExample(SqPriorityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sq_priority
     *
     * @mbg.generated Wed Jan 06 16:46:44 CST 2021
     */
    SqPriority selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sq_priority
     *
     * @mbg.generated Wed Jan 06 16:46:44 CST 2021
     */
    int updateByExampleSelective(@Param("record") SqPriority record, @Param("example") SqPriorityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sq_priority
     *
     * @mbg.generated Wed Jan 06 16:46:44 CST 2021
     */
    int updateByExample(@Param("record") SqPriority record, @Param("example") SqPriorityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sq_priority
     *
     * @mbg.generated Wed Jan 06 16:46:44 CST 2021
     */
    int updateByPrimaryKeySelective(SqPriority record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sq_priority
     *
     * @mbg.generated Wed Jan 06 16:46:44 CST 2021
     */
    int updateByPrimaryKey(SqPriority record);
}