package com.kakarote.crm9.erp.approval.dao;

import com.kakarote.crm9.erp.approval.model.SqState;
import com.kakarote.crm9.erp.approval.model.SqStateExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SqStateMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sq_state
     *
     * @mbg.generated Thu Jan 07 15:54:59 CST 2021
     */
    long countByExample(SqStateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sq_state
     *
     * @mbg.generated Thu Jan 07 15:54:59 CST 2021
     */
    int deleteByExample(SqStateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sq_state
     *
     * @mbg.generated Thu Jan 07 15:54:59 CST 2021
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sq_state
     *
     * @mbg.generated Thu Jan 07 15:54:59 CST 2021
     */
    int insert(SqState record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sq_state
     *
     * @mbg.generated Thu Jan 07 15:54:59 CST 2021
     */
    int insertSelective(SqState record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sq_state
     *
     * @mbg.generated Thu Jan 07 15:54:59 CST 2021
     */
    List<SqState> selectByExample(SqStateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sq_state
     *
     * @mbg.generated Thu Jan 07 15:54:59 CST 2021
     */
    SqState selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sq_state
     *
     * @mbg.generated Thu Jan 07 15:54:59 CST 2021
     */
    int updateByExampleSelective(@Param("record") SqState record, @Param("example") SqStateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sq_state
     *
     * @mbg.generated Thu Jan 07 15:54:59 CST 2021
     */
    int updateByExample(@Param("record") SqState record, @Param("example") SqStateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sq_state
     *
     * @mbg.generated Thu Jan 07 15:54:59 CST 2021
     */
    int updateByPrimaryKeySelective(SqState record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sq_state
     *
     * @mbg.generated Thu Jan 07 15:54:59 CST 2021
     */
    int updateByPrimaryKey(SqState record);
}