package com.kakarote.crm9.erp.approval.dao;

import com.kakarote.crm9.erp.approval.model.SqTask;
import com.kakarote.crm9.erp.approval.model.SqTaskExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SqTaskMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sq_task
     *
     * @mbg.generated Wed Jan 06 16:46:44 CST 2021
     */
    long countByExample(SqTaskExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sq_task
     *
     * @mbg.generated Wed Jan 06 16:46:44 CST 2021
     */
    int deleteByExample(SqTaskExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sq_task
     *
     * @mbg.generated Wed Jan 06 16:46:44 CST 2021
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sq_task
     *
     * @mbg.generated Wed Jan 06 16:46:44 CST 2021
     */
    int insert(SqTask record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sq_task
     *
     * @mbg.generated Wed Jan 06 16:46:44 CST 2021
     */
    int insertSelective(SqTask record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sq_task
     *
     * @mbg.generated Wed Jan 06 16:46:44 CST 2021
     */
    List<SqTask> selectByExample(SqTaskExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sq_task
     *
     * @mbg.generated Wed Jan 06 16:46:44 CST 2021
     */
    SqTask selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sq_task
     *
     * @mbg.generated Wed Jan 06 16:46:44 CST 2021
     */
    int updateByExampleSelective(@Param("record") SqTask record, @Param("example") SqTaskExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sq_task
     *
     * @mbg.generated Wed Jan 06 16:46:44 CST 2021
     */
    int updateByExample(@Param("record") SqTask record, @Param("example") SqTaskExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sq_task
     *
     * @mbg.generated Wed Jan 06 16:46:44 CST 2021
     */
    int updateByPrimaryKeySelective(SqTask record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sq_task
     *
     * @mbg.generated Wed Jan 06 16:46:44 CST 2021
     */
    int updateByPrimaryKey(SqTask record);
}