package com.kakarote.crm9.erp.approval.dao;

import com.kakarote.crm9.erp.approval.model.SqUserTaskExample;
import com.kakarote.crm9.erp.approval.model.SqUserTaskKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SqUserTaskMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sq_user_task
     *
     * @mbg.generated Thu Jan 07 15:54:59 CST 2021
     */
    long countByExample(SqUserTaskExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sq_user_task
     *
     * @mbg.generated Thu Jan 07 15:54:59 CST 2021
     */
    int deleteByExample(SqUserTaskExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sq_user_task
     *
     * @mbg.generated Thu Jan 07 15:54:59 CST 2021
     */
    int deleteByPrimaryKey(SqUserTaskKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sq_user_task
     *
     * @mbg.generated Thu Jan 07 15:54:59 CST 2021
     */
    int insert(SqUserTaskKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sq_user_task
     *
     * @mbg.generated Thu Jan 07 15:54:59 CST 2021
     */
    int insertSelective(SqUserTaskKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sq_user_task
     *
     * @mbg.generated Thu Jan 07 15:54:59 CST 2021
     */
    List<SqUserTaskKey> selectByExample(SqUserTaskExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sq_user_task
     *
     * @mbg.generated Thu Jan 07 15:54:59 CST 2021
     */
    int updateByExampleSelective(@Param("record") SqUserTaskKey record, @Param("example") SqUserTaskExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sq_user_task
     *
     * @mbg.generated Thu Jan 07 15:54:59 CST 2021
     */
    int updateByExample(@Param("record") SqUserTaskKey record, @Param("example") SqUserTaskExample example);
}