package com.kakarote.crm9.erp.approval.dao;

import com.kakarote.crm9.erp.approval.model.SqUserCustomerExample;
import com.kakarote.crm9.erp.approval.model.SqUserCustomerKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SqUserCustomerMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sq_user_customer
     *
     * @mbg.generated Wed Jan 06 16:46:44 CST 2021
     */
    long countByExample(SqUserCustomerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sq_user_customer
     *
     * @mbg.generated Wed Jan 06 16:46:44 CST 2021
     */
    int deleteByExample(SqUserCustomerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sq_user_customer
     *
     * @mbg.generated Wed Jan 06 16:46:44 CST 2021
     */
    int deleteByPrimaryKey(SqUserCustomerKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sq_user_customer
     *
     * @mbg.generated Wed Jan 06 16:46:44 CST 2021
     */
    int insert(SqUserCustomerKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sq_user_customer
     *
     * @mbg.generated Wed Jan 06 16:46:44 CST 2021
     */
    int insertSelective(SqUserCustomerKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sq_user_customer
     *
     * @mbg.generated Wed Jan 06 16:46:44 CST 2021
     */
    List<SqUserCustomerKey> selectByExample(SqUserCustomerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sq_user_customer
     *
     * @mbg.generated Wed Jan 06 16:46:44 CST 2021
     */
    int updateByExampleSelective(@Param("record") SqUserCustomerKey record, @Param("example") SqUserCustomerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sq_user_customer
     *
     * @mbg.generated Wed Jan 06 16:46:44 CST 2021
     */
    int updateByExample(@Param("record") SqUserCustomerKey record, @Param("example") SqUserCustomerExample example);
}