package com.kakarote.crm9.erp.approval.dao;

import com.kakarote.crm9.erp.approval.model.SqUserUserExample;
import com.kakarote.crm9.erp.approval.model.SqUserUserKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SqUserUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sq_user_user
     *
     * @mbg.generated Thu Jan 07 15:54:59 CST 2021
     */
    long countByExample(SqUserUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sq_user_user
     *
     * @mbg.generated Thu Jan 07 15:54:59 CST 2021
     */
    int deleteByExample(SqUserUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sq_user_user
     *
     * @mbg.generated Thu Jan 07 15:54:59 CST 2021
     */
    int deleteByPrimaryKey(SqUserUserKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sq_user_user
     *
     * @mbg.generated Thu Jan 07 15:54:59 CST 2021
     */
    int insert(SqUserUserKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sq_user_user
     *
     * @mbg.generated Thu Jan 07 15:54:59 CST 2021
     */
    int insertSelective(SqUserUserKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sq_user_user
     *
     * @mbg.generated Thu Jan 07 15:54:59 CST 2021
     */
    List<SqUserUserKey> selectByExample(SqUserUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sq_user_user
     *
     * @mbg.generated Thu Jan 07 15:54:59 CST 2021
     */
    int updateByExampleSelective(@Param("record") SqUserUserKey record, @Param("example") SqUserUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sq_user_user
     *
     * @mbg.generated Thu Jan 07 15:54:59 CST 2021
     */
    int updateByExample(@Param("record") SqUserUserKey record, @Param("example") SqUserUserExample example);
}