package com.kakarote.crm9.erp.log.dao;

import com.kakarote.crm9.erp.log.model.Log;
import com.kakarote.crm9.erp.log.model.LogExample;
import com.kakarote.crm9.erp.log.model.LogWithBLOBs;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface LogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table log
     *
     * @mbg.generated Sat Jan 09 15:29:19 CST 2021
     */
    long countByExample(LogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table log
     *
     * @mbg.generated Sat Jan 09 15:29:19 CST 2021
     */
    int deleteByExample(LogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table log
     *
     * @mbg.generated Sat Jan 09 15:29:19 CST 2021
     */
    int deleteByPrimaryKey(Integer logid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table log
     *
     * @mbg.generated Sat Jan 09 15:29:19 CST 2021
     */
    int insert(Log record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table log
     *
     * @mbg.generated Sat Jan 09 15:29:19 CST 2021
     */
    int insertSelective(LogWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table log
     *
     * @mbg.generated Sat Jan 09 15:29:19 CST 2021
     */
    List<LogWithBLOBs> selectByExampleWithBLOBs(LogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table log
     *
     * @mbg.generated Sat Jan 09 15:29:19 CST 2021
     */
    List<Log> selectByExample(LogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table log
     *
     * @mbg.generated Sat Jan 09 15:29:19 CST 2021
     */
    LogWithBLOBs selectByPrimaryKey(Integer logid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table log
     *
     * @mbg.generated Sat Jan 09 15:29:19 CST 2021
     */
    int updateByExampleSelective(@Param("record") LogWithBLOBs record, @Param("example") LogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table log
     *
     * @mbg.generated Sat Jan 09 15:29:19 CST 2021
     */
    int updateByExampleWithBLOBs(@Param("record") LogWithBLOBs record, @Param("example") LogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table log
     *
     * @mbg.generated Sat Jan 09 15:29:19 CST 2021
     */
    int updateByExample(@Param("record") Log record, @Param("example") LogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table log
     *
     * @mbg.generated Sat Jan 09 15:29:19 CST 2021
     */
    int updateByPrimaryKeySelective(LogWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table log
     *
     * @mbg.generated Sat Jan 09 15:29:19 CST 2021
     */
    int updateByPrimaryKeyWithBLOBs(LogWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table log
     *
     * @mbg.generated Sat Jan 09 15:29:19 CST 2021
     */
    int updateByPrimaryKey(Log record);
    List<Log> selectAll();

    List<Log> selectById();
}