package com.kakarote.crm9.erp.bi.dao;

import com.kakarote.crm9.erp.bi.model.BiUserCustomer;
import com.kakarote.crm9.erp.bi.model.BiUserCustomerExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface BiUserCustomerMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bi_user_customer
     *
     * @mbg.generated Thu Jan 07 23:11:28 CST 2021
     */
    long countByExample(BiUserCustomerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bi_user_customer
     *
     * @mbg.generated Thu Jan 07 23:11:28 CST 2021
     */
    int deleteByExample(BiUserCustomerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bi_user_customer
     *
     * @mbg.generated Thu Jan 07 23:11:28 CST 2021
     */
    int deleteByPrimaryKey(Integer bid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bi_user_customer
     *
     * @mbg.generated Thu Jan 07 23:11:28 CST 2021
     */
    int insert(BiUserCustomer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bi_user_customer
     *
     * @mbg.generated Thu Jan 07 23:11:28 CST 2021
     */
    int insertSelective(BiUserCustomer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bi_user_customer
     *
     * @mbg.generated Thu Jan 07 23:11:28 CST 2021
     */
    List<BiUserCustomer> selectByExample(BiUserCustomerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bi_user_customer
     *
     * @mbg.generated Thu Jan 07 23:11:28 CST 2021
     */
    BiUserCustomer selectByPrimaryKey(Integer bid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bi_user_customer
     *
     * @mbg.generated Thu Jan 07 23:11:28 CST 2021
     */
    int updateByExampleSelective(@Param("record") BiUserCustomer record, @Param("example") BiUserCustomerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bi_user_customer
     *
     * @mbg.generated Thu Jan 07 23:11:28 CST 2021
     */
    int updateByExample(@Param("record") BiUserCustomer record, @Param("example") BiUserCustomerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bi_user_customer
     *
     * @mbg.generated Thu Jan 07 23:11:28 CST 2021
     */
    int updateByPrimaryKeySelective(BiUserCustomer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bi_user_customer
     *
     * @mbg.generated Thu Jan 07 23:11:28 CST 2021
     */
    int updateByPrimaryKey(BiUserCustomer record);
}