package com.kakarote.crm9.erp.bi.model;

import java.util.ArrayList;
import java.util.List;

public class BiUserCustomerExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table bi_user_customer
     *
     * @mbg.generated Thu Jan 07 23:11:28 CST 2021
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table bi_user_customer
     *
     * @mbg.generated Thu Jan 07 23:11:28 CST 2021
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table bi_user_customer
     *
     * @mbg.generated Thu Jan 07 23:11:28 CST 2021
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bi_user_customer
     *
     * @mbg.generated Thu Jan 07 23:11:28 CST 2021
     */
    public BiUserCustomerExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bi_user_customer
     *
     * @mbg.generated Thu Jan 07 23:11:28 CST 2021
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bi_user_customer
     *
     * @mbg.generated Thu Jan 07 23:11:28 CST 2021
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bi_user_customer
     *
     * @mbg.generated Thu Jan 07 23:11:28 CST 2021
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bi_user_customer
     *
     * @mbg.generated Thu Jan 07 23:11:28 CST 2021
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bi_user_customer
     *
     * @mbg.generated Thu Jan 07 23:11:28 CST 2021
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bi_user_customer
     *
     * @mbg.generated Thu Jan 07 23:11:28 CST 2021
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bi_user_customer
     *
     * @mbg.generated Thu Jan 07 23:11:28 CST 2021
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bi_user_customer
     *
     * @mbg.generated Thu Jan 07 23:11:28 CST 2021
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bi_user_customer
     *
     * @mbg.generated Thu Jan 07 23:11:28 CST 2021
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bi_user_customer
     *
     * @mbg.generated Thu Jan 07 23:11:28 CST 2021
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table bi_user_customer
     *
     * @mbg.generated Thu Jan 07 23:11:28 CST 2021
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andBidIsNull() {
            addCriterion("bid is null");
            return (Criteria) this;
        }

        public Criteria andBidIsNotNull() {
            addCriterion("bid is not null");
            return (Criteria) this;
        }

        public Criteria andBidEqualTo(Integer value) {
            addCriterion("bid =", value, "bid");
            return (Criteria) this;
        }

        public Criteria andBidNotEqualTo(Integer value) {
            addCriterion("bid <>", value, "bid");
            return (Criteria) this;
        }

        public Criteria andBidGreaterThan(Integer value) {
            addCriterion("bid >", value, "bid");
            return (Criteria) this;
        }

        public Criteria andBidGreaterThanOrEqualTo(Integer value) {
            addCriterion("bid >=", value, "bid");
            return (Criteria) this;
        }

        public Criteria andBidLessThan(Integer value) {
            addCriterion("bid <", value, "bid");
            return (Criteria) this;
        }

        public Criteria andBidLessThanOrEqualTo(Integer value) {
            addCriterion("bid <=", value, "bid");
            return (Criteria) this;
        }

        public Criteria andBidIn(List<Integer> values) {
            addCriterion("bid in", values, "bid");
            return (Criteria) this;
        }

        public Criteria andBidNotIn(List<Integer> values) {
            addCriterion("bid not in", values, "bid");
            return (Criteria) this;
        }

        public Criteria andBidBetween(Integer value1, Integer value2) {
            addCriterion("bid between", value1, value2, "bid");
            return (Criteria) this;
        }

        public Criteria andBidNotBetween(Integer value1, Integer value2) {
            addCriterion("bid not between", value1, value2, "bid");
            return (Criteria) this;
        }

        public Criteria andUnameIsNull() {
            addCriterion("uname is null");
            return (Criteria) this;
        }

        public Criteria andUnameIsNotNull() {
            addCriterion("uname is not null");
            return (Criteria) this;
        }

        public Criteria andUnameEqualTo(String value) {
            addCriterion("uname =", value, "uname");
            return (Criteria) this;
        }

        public Criteria andUnameNotEqualTo(String value) {
            addCriterion("uname <>", value, "uname");
            return (Criteria) this;
        }

        public Criteria andUnameGreaterThan(String value) {
            addCriterion("uname >", value, "uname");
            return (Criteria) this;
        }

        public Criteria andUnameGreaterThanOrEqualTo(String value) {
            addCriterion("uname >=", value, "uname");
            return (Criteria) this;
        }

        public Criteria andUnameLessThan(String value) {
            addCriterion("uname <", value, "uname");
            return (Criteria) this;
        }

        public Criteria andUnameLessThanOrEqualTo(String value) {
            addCriterion("uname <=", value, "uname");
            return (Criteria) this;
        }

        public Criteria andUnameLike(String value) {
            addCriterion("uname like", value, "uname");
            return (Criteria) this;
        }

        public Criteria andUnameNotLike(String value) {
            addCriterion("uname not like", value, "uname");
            return (Criteria) this;
        }

        public Criteria andUnameIn(List<String> values) {
            addCriterion("uname in", values, "uname");
            return (Criteria) this;
        }

        public Criteria andUnameNotIn(List<String> values) {
            addCriterion("uname not in", values, "uname");
            return (Criteria) this;
        }

        public Criteria andUnameBetween(String value1, String value2) {
            addCriterion("uname between", value1, value2, "uname");
            return (Criteria) this;
        }

        public Criteria andUnameNotBetween(String value1, String value2) {
            addCriterion("uname not between", value1, value2, "uname");
            return (Criteria) this;
        }

        public Criteria andAdcunumIsNull() {
            addCriterion("adcunum is null");
            return (Criteria) this;
        }

        public Criteria andAdcunumIsNotNull() {
            addCriterion("adcunum is not null");
            return (Criteria) this;
        }

        public Criteria andAdcunumEqualTo(Integer value) {
            addCriterion("adcunum =", value, "adcunum");
            return (Criteria) this;
        }

        public Criteria andAdcunumNotEqualTo(Integer value) {
            addCriterion("adcunum <>", value, "adcunum");
            return (Criteria) this;
        }

        public Criteria andAdcunumGreaterThan(Integer value) {
            addCriterion("adcunum >", value, "adcunum");
            return (Criteria) this;
        }

        public Criteria andAdcunumGreaterThanOrEqualTo(Integer value) {
            addCriterion("adcunum >=", value, "adcunum");
            return (Criteria) this;
        }

        public Criteria andAdcunumLessThan(Integer value) {
            addCriterion("adcunum <", value, "adcunum");
            return (Criteria) this;
        }

        public Criteria andAdcunumLessThanOrEqualTo(Integer value) {
            addCriterion("adcunum <=", value, "adcunum");
            return (Criteria) this;
        }

        public Criteria andAdcunumIn(List<Integer> values) {
            addCriterion("adcunum in", values, "adcunum");
            return (Criteria) this;
        }

        public Criteria andAdcunumNotIn(List<Integer> values) {
            addCriterion("adcunum not in", values, "adcunum");
            return (Criteria) this;
        }

        public Criteria andAdcunumBetween(Integer value1, Integer value2) {
            addCriterion("adcunum between", value1, value2, "adcunum");
            return (Criteria) this;
        }

        public Criteria andAdcunumNotBetween(Integer value1, Integer value2) {
            addCriterion("adcunum not between", value1, value2, "adcunum");
            return (Criteria) this;
        }

        public Criteria andDealnumIsNull() {
            addCriterion("dealnum is null");
            return (Criteria) this;
        }

        public Criteria andDealnumIsNotNull() {
            addCriterion("dealnum is not null");
            return (Criteria) this;
        }

        public Criteria andDealnumEqualTo(Integer value) {
            addCriterion("dealnum =", value, "dealnum");
            return (Criteria) this;
        }

        public Criteria andDealnumNotEqualTo(Integer value) {
            addCriterion("dealnum <>", value, "dealnum");
            return (Criteria) this;
        }

        public Criteria andDealnumGreaterThan(Integer value) {
            addCriterion("dealnum >", value, "dealnum");
            return (Criteria) this;
        }

        public Criteria andDealnumGreaterThanOrEqualTo(Integer value) {
            addCriterion("dealnum >=", value, "dealnum");
            return (Criteria) this;
        }

        public Criteria andDealnumLessThan(Integer value) {
            addCriterion("dealnum <", value, "dealnum");
            return (Criteria) this;
        }

        public Criteria andDealnumLessThanOrEqualTo(Integer value) {
            addCriterion("dealnum <=", value, "dealnum");
            return (Criteria) this;
        }

        public Criteria andDealnumIn(List<Integer> values) {
            addCriterion("dealnum in", values, "dealnum");
            return (Criteria) this;
        }

        public Criteria andDealnumNotIn(List<Integer> values) {
            addCriterion("dealnum not in", values, "dealnum");
            return (Criteria) this;
        }

        public Criteria andDealnumBetween(Integer value1, Integer value2) {
            addCriterion("dealnum between", value1, value2, "dealnum");
            return (Criteria) this;
        }

        public Criteria andDealnumNotBetween(Integer value1, Integer value2) {
            addCriterion("dealnum not between", value1, value2, "dealnum");
            return (Criteria) this;
        }

        public Criteria andDealrateIsNull() {
            addCriterion("dealrate is null");
            return (Criteria) this;
        }

        public Criteria andDealrateIsNotNull() {
            addCriterion("dealrate is not null");
            return (Criteria) this;
        }

        public Criteria andDealrateEqualTo(String value) {
            addCriterion("dealrate =", value, "dealrate");
            return (Criteria) this;
        }

        public Criteria andDealrateNotEqualTo(String value) {
            addCriterion("dealrate <>", value, "dealrate");
            return (Criteria) this;
        }

        public Criteria andDealrateGreaterThan(String value) {
            addCriterion("dealrate >", value, "dealrate");
            return (Criteria) this;
        }

        public Criteria andDealrateGreaterThanOrEqualTo(String value) {
            addCriterion("dealrate >=", value, "dealrate");
            return (Criteria) this;
        }

        public Criteria andDealrateLessThan(String value) {
            addCriterion("dealrate <", value, "dealrate");
            return (Criteria) this;
        }

        public Criteria andDealrateLessThanOrEqualTo(String value) {
            addCriterion("dealrate <=", value, "dealrate");
            return (Criteria) this;
        }

        public Criteria andDealrateLike(String value) {
            addCriterion("dealrate like", value, "dealrate");
            return (Criteria) this;
        }

        public Criteria andDealrateNotLike(String value) {
            addCriterion("dealrate not like", value, "dealrate");
            return (Criteria) this;
        }

        public Criteria andDealrateIn(List<String> values) {
            addCriterion("dealrate in", values, "dealrate");
            return (Criteria) this;
        }

        public Criteria andDealrateNotIn(List<String> values) {
            addCriterion("dealrate not in", values, "dealrate");
            return (Criteria) this;
        }

        public Criteria andDealrateBetween(String value1, String value2) {
            addCriterion("dealrate between", value1, value2, "dealrate");
            return (Criteria) this;
        }

        public Criteria andDealrateNotBetween(String value1, String value2) {
            addCriterion("dealrate not between", value1, value2, "dealrate");
            return (Criteria) this;
        }

        public Criteria andContractmoneyIsNull() {
            addCriterion("contractmoney is null");
            return (Criteria) this;
        }

        public Criteria andContractmoneyIsNotNull() {
            addCriterion("contractmoney is not null");
            return (Criteria) this;
        }

        public Criteria andContractmoneyEqualTo(Integer value) {
            addCriterion("contractmoney =", value, "contractmoney");
            return (Criteria) this;
        }

        public Criteria andContractmoneyNotEqualTo(Integer value) {
            addCriterion("contractmoney <>", value, "contractmoney");
            return (Criteria) this;
        }

        public Criteria andContractmoneyGreaterThan(Integer value) {
            addCriterion("contractmoney >", value, "contractmoney");
            return (Criteria) this;
        }

        public Criteria andContractmoneyGreaterThanOrEqualTo(Integer value) {
            addCriterion("contractmoney >=", value, "contractmoney");
            return (Criteria) this;
        }

        public Criteria andContractmoneyLessThan(Integer value) {
            addCriterion("contractmoney <", value, "contractmoney");
            return (Criteria) this;
        }

        public Criteria andContractmoneyLessThanOrEqualTo(Integer value) {
            addCriterion("contractmoney <=", value, "contractmoney");
            return (Criteria) this;
        }

        public Criteria andContractmoneyIn(List<Integer> values) {
            addCriterion("contractmoney in", values, "contractmoney");
            return (Criteria) this;
        }

        public Criteria andContractmoneyNotIn(List<Integer> values) {
            addCriterion("contractmoney not in", values, "contractmoney");
            return (Criteria) this;
        }

        public Criteria andContractmoneyBetween(Integer value1, Integer value2) {
            addCriterion("contractmoney between", value1, value2, "contractmoney");
            return (Criteria) this;
        }

        public Criteria andContractmoneyNotBetween(Integer value1, Integer value2) {
            addCriterion("contractmoney not between", value1, value2, "contractmoney");
            return (Criteria) this;
        }

        public Criteria andReturnmoneyIsNull() {
            addCriterion("returnmoney is null");
            return (Criteria) this;
        }

        public Criteria andReturnmoneyIsNotNull() {
            addCriterion("returnmoney is not null");
            return (Criteria) this;
        }

        public Criteria andReturnmoneyEqualTo(Integer value) {
            addCriterion("returnmoney =", value, "returnmoney");
            return (Criteria) this;
        }

        public Criteria andReturnmoneyNotEqualTo(Integer value) {
            addCriterion("returnmoney <>", value, "returnmoney");
            return (Criteria) this;
        }

        public Criteria andReturnmoneyGreaterThan(Integer value) {
            addCriterion("returnmoney >", value, "returnmoney");
            return (Criteria) this;
        }

        public Criteria andReturnmoneyGreaterThanOrEqualTo(Integer value) {
            addCriterion("returnmoney >=", value, "returnmoney");
            return (Criteria) this;
        }

        public Criteria andReturnmoneyLessThan(Integer value) {
            addCriterion("returnmoney <", value, "returnmoney");
            return (Criteria) this;
        }

        public Criteria andReturnmoneyLessThanOrEqualTo(Integer value) {
            addCriterion("returnmoney <=", value, "returnmoney");
            return (Criteria) this;
        }

        public Criteria andReturnmoneyIn(List<Integer> values) {
            addCriterion("returnmoney in", values, "returnmoney");
            return (Criteria) this;
        }

        public Criteria andReturnmoneyNotIn(List<Integer> values) {
            addCriterion("returnmoney not in", values, "returnmoney");
            return (Criteria) this;
        }

        public Criteria andReturnmoneyBetween(Integer value1, Integer value2) {
            addCriterion("returnmoney between", value1, value2, "returnmoney");
            return (Criteria) this;
        }

        public Criteria andReturnmoneyNotBetween(Integer value1, Integer value2) {
            addCriterion("returnmoney not between", value1, value2, "returnmoney");
            return (Criteria) this;
        }

        public Criteria andNoremoneyIsNull() {
            addCriterion("noremoney is null");
            return (Criteria) this;
        }

        public Criteria andNoremoneyIsNotNull() {
            addCriterion("noremoney is not null");
            return (Criteria) this;
        }

        public Criteria andNoremoneyEqualTo(Integer value) {
            addCriterion("noremoney =", value, "noremoney");
            return (Criteria) this;
        }

        public Criteria andNoremoneyNotEqualTo(Integer value) {
            addCriterion("noremoney <>", value, "noremoney");
            return (Criteria) this;
        }

        public Criteria andNoremoneyGreaterThan(Integer value) {
            addCriterion("noremoney >", value, "noremoney");
            return (Criteria) this;
        }

        public Criteria andNoremoneyGreaterThanOrEqualTo(Integer value) {
            addCriterion("noremoney >=", value, "noremoney");
            return (Criteria) this;
        }

        public Criteria andNoremoneyLessThan(Integer value) {
            addCriterion("noremoney <", value, "noremoney");
            return (Criteria) this;
        }

        public Criteria andNoremoneyLessThanOrEqualTo(Integer value) {
            addCriterion("noremoney <=", value, "noremoney");
            return (Criteria) this;
        }

        public Criteria andNoremoneyIn(List<Integer> values) {
            addCriterion("noremoney in", values, "noremoney");
            return (Criteria) this;
        }

        public Criteria andNoremoneyNotIn(List<Integer> values) {
            addCriterion("noremoney not in", values, "noremoney");
            return (Criteria) this;
        }

        public Criteria andNoremoneyBetween(Integer value1, Integer value2) {
            addCriterion("noremoney between", value1, value2, "noremoney");
            return (Criteria) this;
        }

        public Criteria andNoremoneyNotBetween(Integer value1, Integer value2) {
            addCriterion("noremoney not between", value1, value2, "noremoney");
            return (Criteria) this;
        }

        public Criteria andRemoneyrateIsNull() {
            addCriterion("remoneyrate is null");
            return (Criteria) this;
        }

        public Criteria andRemoneyrateIsNotNull() {
            addCriterion("remoneyrate is not null");
            return (Criteria) this;
        }

        public Criteria andRemoneyrateEqualTo(String value) {
            addCriterion("remoneyrate =", value, "remoneyrate");
            return (Criteria) this;
        }

        public Criteria andRemoneyrateNotEqualTo(String value) {
            addCriterion("remoneyrate <>", value, "remoneyrate");
            return (Criteria) this;
        }

        public Criteria andRemoneyrateGreaterThan(String value) {
            addCriterion("remoneyrate >", value, "remoneyrate");
            return (Criteria) this;
        }

        public Criteria andRemoneyrateGreaterThanOrEqualTo(String value) {
            addCriterion("remoneyrate >=", value, "remoneyrate");
            return (Criteria) this;
        }

        public Criteria andRemoneyrateLessThan(String value) {
            addCriterion("remoneyrate <", value, "remoneyrate");
            return (Criteria) this;
        }

        public Criteria andRemoneyrateLessThanOrEqualTo(String value) {
            addCriterion("remoneyrate <=", value, "remoneyrate");
            return (Criteria) this;
        }

        public Criteria andRemoneyrateLike(String value) {
            addCriterion("remoneyrate like", value, "remoneyrate");
            return (Criteria) this;
        }

        public Criteria andRemoneyrateNotLike(String value) {
            addCriterion("remoneyrate not like", value, "remoneyrate");
            return (Criteria) this;
        }

        public Criteria andRemoneyrateIn(List<String> values) {
            addCriterion("remoneyrate in", values, "remoneyrate");
            return (Criteria) this;
        }

        public Criteria andRemoneyrateNotIn(List<String> values) {
            addCriterion("remoneyrate not in", values, "remoneyrate");
            return (Criteria) this;
        }

        public Criteria andRemoneyrateBetween(String value1, String value2) {
            addCriterion("remoneyrate between", value1, value2, "remoneyrate");
            return (Criteria) this;
        }

        public Criteria andRemoneyrateNotBetween(String value1, String value2) {
            addCriterion("remoneyrate not between", value1, value2, "remoneyrate");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table bi_user_customer
     *
     * @mbg.generated do_not_delete_during_merge Thu Jan 07 23:11:28 CST 2021
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table bi_user_customer
     *
     * @mbg.generated Thu Jan 07 23:11:28 CST 2021
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}