package com.kakarote.crm9.erp.backlog.model;

import java.util.ArrayList;
import java.util.List;

public class ClientExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table client
     *
     * @mbg.generated Wed Jan 06 15:32:23 CST 2021
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table client
     *
     * @mbg.generated Wed Jan 06 15:32:23 CST 2021
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table client
     *
     * @mbg.generated Wed Jan 06 15:32:23 CST 2021
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table client
     *
     * @mbg.generated Wed Jan 06 15:32:23 CST 2021
     */
    public ClientExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table client
     *
     * @mbg.generated Wed Jan 06 15:32:23 CST 2021
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table client
     *
     * @mbg.generated Wed Jan 06 15:32:23 CST 2021
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table client
     *
     * @mbg.generated Wed Jan 06 15:32:23 CST 2021
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table client
     *
     * @mbg.generated Wed Jan 06 15:32:23 CST 2021
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table client
     *
     * @mbg.generated Wed Jan 06 15:32:23 CST 2021
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table client
     *
     * @mbg.generated Wed Jan 06 15:32:23 CST 2021
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table client
     *
     * @mbg.generated Wed Jan 06 15:32:23 CST 2021
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table client
     *
     * @mbg.generated Wed Jan 06 15:32:23 CST 2021
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table client
     *
     * @mbg.generated Wed Jan 06 15:32:23 CST 2021
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table client
     *
     * @mbg.generated Wed Jan 06 15:32:23 CST 2021
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table client
     *
     * @mbg.generated Wed Jan 06 15:32:23 CST 2021
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andCidIsNull() {
            addCriterion("cid is null");
            return (Criteria) this;
        }

        public Criteria andCidIsNotNull() {
            addCriterion("cid is not null");
            return (Criteria) this;
        }

        public Criteria andCidEqualTo(Integer value) {
            addCriterion("cid =", value, "cid");
            return (Criteria) this;
        }

        public Criteria andCidNotEqualTo(Integer value) {
            addCriterion("cid <>", value, "cid");
            return (Criteria) this;
        }

        public Criteria andCidGreaterThan(Integer value) {
            addCriterion("cid >", value, "cid");
            return (Criteria) this;
        }

        public Criteria andCidGreaterThanOrEqualTo(Integer value) {
            addCriterion("cid >=", value, "cid");
            return (Criteria) this;
        }

        public Criteria andCidLessThan(Integer value) {
            addCriterion("cid <", value, "cid");
            return (Criteria) this;
        }

        public Criteria andCidLessThanOrEqualTo(Integer value) {
            addCriterion("cid <=", value, "cid");
            return (Criteria) this;
        }

        public Criteria andCidIn(List<Integer> values) {
            addCriterion("cid in", values, "cid");
            return (Criteria) this;
        }

        public Criteria andCidNotIn(List<Integer> values) {
            addCriterion("cid not in", values, "cid");
            return (Criteria) this;
        }

        public Criteria andCidBetween(Integer value1, Integer value2) {
            addCriterion("cid between", value1, value2, "cid");
            return (Criteria) this;
        }

        public Criteria andCidNotBetween(Integer value1, Integer value2) {
            addCriterion("cid not between", value1, value2, "cid");
            return (Criteria) this;
        }

        public Criteria andCnameIsNull() {
            addCriterion("cname is null");
            return (Criteria) this;
        }

        public Criteria andCnameIsNotNull() {
            addCriterion("cname is not null");
            return (Criteria) this;
        }

        public Criteria andCnameEqualTo(String value) {
            addCriterion("cname =", value, "cname");
            return (Criteria) this;
        }

        public Criteria andCnameNotEqualTo(String value) {
            addCriterion("cname <>", value, "cname");
            return (Criteria) this;
        }

        public Criteria andCnameGreaterThan(String value) {
            addCriterion("cname >", value, "cname");
            return (Criteria) this;
        }

        public Criteria andCnameGreaterThanOrEqualTo(String value) {
            addCriterion("cname >=", value, "cname");
            return (Criteria) this;
        }

        public Criteria andCnameLessThan(String value) {
            addCriterion("cname <", value, "cname");
            return (Criteria) this;
        }

        public Criteria andCnameLessThanOrEqualTo(String value) {
            addCriterion("cname <=", value, "cname");
            return (Criteria) this;
        }

        public Criteria andCnameLike(String value) {
            addCriterion("cname like", value, "cname");
            return (Criteria) this;
        }

        public Criteria andCnameNotLike(String value) {
            addCriterion("cname not like", value, "cname");
            return (Criteria) this;
        }

        public Criteria andCnameIn(List<String> values) {
            addCriterion("cname in", values, "cname");
            return (Criteria) this;
        }

        public Criteria andCnameNotIn(List<String> values) {
            addCriterion("cname not in", values, "cname");
            return (Criteria) this;
        }

        public Criteria andCnameBetween(String value1, String value2) {
            addCriterion("cname between", value1, value2, "cname");
            return (Criteria) this;
        }

        public Criteria andCnameNotBetween(String value1, String value2) {
            addCriterion("cname not between", value1, value2, "cname");
            return (Criteria) this;
        }

        public Criteria andCsourceIsNull() {
            addCriterion("csource is null");
            return (Criteria) this;
        }

        public Criteria andCsourceIsNotNull() {
            addCriterion("csource is not null");
            return (Criteria) this;
        }

        public Criteria andCsourceEqualTo(String value) {
            addCriterion("csource =", value, "csource");
            return (Criteria) this;
        }

        public Criteria andCsourceNotEqualTo(String value) {
            addCriterion("csource <>", value, "csource");
            return (Criteria) this;
        }

        public Criteria andCsourceGreaterThan(String value) {
            addCriterion("csource >", value, "csource");
            return (Criteria) this;
        }

        public Criteria andCsourceGreaterThanOrEqualTo(String value) {
            addCriterion("csource >=", value, "csource");
            return (Criteria) this;
        }

        public Criteria andCsourceLessThan(String value) {
            addCriterion("csource <", value, "csource");
            return (Criteria) this;
        }

        public Criteria andCsourceLessThanOrEqualTo(String value) {
            addCriterion("csource <=", value, "csource");
            return (Criteria) this;
        }

        public Criteria andCsourceLike(String value) {
            addCriterion("csource like", value, "csource");
            return (Criteria) this;
        }

        public Criteria andCsourceNotLike(String value) {
            addCriterion("csource not like", value, "csource");
            return (Criteria) this;
        }

        public Criteria andCsourceIn(List<String> values) {
            addCriterion("csource in", values, "csource");
            return (Criteria) this;
        }

        public Criteria andCsourceNotIn(List<String> values) {
            addCriterion("csource not in", values, "csource");
            return (Criteria) this;
        }

        public Criteria andCsourceBetween(String value1, String value2) {
            addCriterion("csource between", value1, value2, "csource");
            return (Criteria) this;
        }

        public Criteria andCsourceNotBetween(String value1, String value2) {
            addCriterion("csource not between", value1, value2, "csource");
            return (Criteria) this;
        }

        public Criteria andCtelIsNull() {
            addCriterion("ctel is null");
            return (Criteria) this;
        }

        public Criteria andCtelIsNotNull() {
            addCriterion("ctel is not null");
            return (Criteria) this;
        }

        public Criteria andCtelEqualTo(String value) {
            addCriterion("ctel =", value, "ctel");
            return (Criteria) this;
        }

        public Criteria andCtelNotEqualTo(String value) {
            addCriterion("ctel <>", value, "ctel");
            return (Criteria) this;
        }

        public Criteria andCtelGreaterThan(String value) {
            addCriterion("ctel >", value, "ctel");
            return (Criteria) this;
        }

        public Criteria andCtelGreaterThanOrEqualTo(String value) {
            addCriterion("ctel >=", value, "ctel");
            return (Criteria) this;
        }

        public Criteria andCtelLessThan(String value) {
            addCriterion("ctel <", value, "ctel");
            return (Criteria) this;
        }

        public Criteria andCtelLessThanOrEqualTo(String value) {
            addCriterion("ctel <=", value, "ctel");
            return (Criteria) this;
        }

        public Criteria andCtelLike(String value) {
            addCriterion("ctel like", value, "ctel");
            return (Criteria) this;
        }

        public Criteria andCtelNotLike(String value) {
            addCriterion("ctel not like", value, "ctel");
            return (Criteria) this;
        }

        public Criteria andCtelIn(List<String> values) {
            addCriterion("ctel in", values, "ctel");
            return (Criteria) this;
        }

        public Criteria andCtelNotIn(List<String> values) {
            addCriterion("ctel not in", values, "ctel");
            return (Criteria) this;
        }

        public Criteria andCtelBetween(String value1, String value2) {
            addCriterion("ctel between", value1, value2, "ctel");
            return (Criteria) this;
        }

        public Criteria andCtelNotBetween(String value1, String value2) {
            addCriterion("ctel not between", value1, value2, "ctel");
            return (Criteria) this;
        }

        public Criteria andCcallIsNull() {
            addCriterion("ccall is null");
            return (Criteria) this;
        }

        public Criteria andCcallIsNotNull() {
            addCriterion("ccall is not null");
            return (Criteria) this;
        }

        public Criteria andCcallEqualTo(String value) {
            addCriterion("ccall =", value, "ccall");
            return (Criteria) this;
        }

        public Criteria andCcallNotEqualTo(String value) {
            addCriterion("ccall <>", value, "ccall");
            return (Criteria) this;
        }

        public Criteria andCcallGreaterThan(String value) {
            addCriterion("ccall >", value, "ccall");
            return (Criteria) this;
        }

        public Criteria andCcallGreaterThanOrEqualTo(String value) {
            addCriterion("ccall >=", value, "ccall");
            return (Criteria) this;
        }

        public Criteria andCcallLessThan(String value) {
            addCriterion("ccall <", value, "ccall");
            return (Criteria) this;
        }

        public Criteria andCcallLessThanOrEqualTo(String value) {
            addCriterion("ccall <=", value, "ccall");
            return (Criteria) this;
        }

        public Criteria andCcallLike(String value) {
            addCriterion("ccall like", value, "ccall");
            return (Criteria) this;
        }

        public Criteria andCcallNotLike(String value) {
            addCriterion("ccall not like", value, "ccall");
            return (Criteria) this;
        }

        public Criteria andCcallIn(List<String> values) {
            addCriterion("ccall in", values, "ccall");
            return (Criteria) this;
        }

        public Criteria andCcallNotIn(List<String> values) {
            addCriterion("ccall not in", values, "ccall");
            return (Criteria) this;
        }

        public Criteria andCcallBetween(String value1, String value2) {
            addCriterion("ccall between", value1, value2, "ccall");
            return (Criteria) this;
        }

        public Criteria andCcallNotBetween(String value1, String value2) {
            addCriterion("ccall not between", value1, value2, "ccall");
            return (Criteria) this;
        }

        public Criteria andCwebIsNull() {
            addCriterion("cweb is null");
            return (Criteria) this;
        }

        public Criteria andCwebIsNotNull() {
            addCriterion("cweb is not null");
            return (Criteria) this;
        }

        public Criteria andCwebEqualTo(String value) {
            addCriterion("cweb =", value, "cweb");
            return (Criteria) this;
        }

        public Criteria andCwebNotEqualTo(String value) {
            addCriterion("cweb <>", value, "cweb");
            return (Criteria) this;
        }

        public Criteria andCwebGreaterThan(String value) {
            addCriterion("cweb >", value, "cweb");
            return (Criteria) this;
        }

        public Criteria andCwebGreaterThanOrEqualTo(String value) {
            addCriterion("cweb >=", value, "cweb");
            return (Criteria) this;
        }

        public Criteria andCwebLessThan(String value) {
            addCriterion("cweb <", value, "cweb");
            return (Criteria) this;
        }

        public Criteria andCwebLessThanOrEqualTo(String value) {
            addCriterion("cweb <=", value, "cweb");
            return (Criteria) this;
        }

        public Criteria andCwebLike(String value) {
            addCriterion("cweb like", value, "cweb");
            return (Criteria) this;
        }

        public Criteria andCwebNotLike(String value) {
            addCriterion("cweb not like", value, "cweb");
            return (Criteria) this;
        }

        public Criteria andCwebIn(List<String> values) {
            addCriterion("cweb in", values, "cweb");
            return (Criteria) this;
        }

        public Criteria andCwebNotIn(List<String> values) {
            addCriterion("cweb not in", values, "cweb");
            return (Criteria) this;
        }

        public Criteria andCwebBetween(String value1, String value2) {
            addCriterion("cweb between", value1, value2, "cweb");
            return (Criteria) this;
        }

        public Criteria andCwebNotBetween(String value1, String value2) {
            addCriterion("cweb not between", value1, value2, "cweb");
            return (Criteria) this;
        }

        public Criteria andCemailIsNull() {
            addCriterion("cemail is null");
            return (Criteria) this;
        }

        public Criteria andCemailIsNotNull() {
            addCriterion("cemail is not null");
            return (Criteria) this;
        }

        public Criteria andCemailEqualTo(String value) {
            addCriterion("cemail =", value, "cemail");
            return (Criteria) this;
        }

        public Criteria andCemailNotEqualTo(String value) {
            addCriterion("cemail <>", value, "cemail");
            return (Criteria) this;
        }

        public Criteria andCemailGreaterThan(String value) {
            addCriterion("cemail >", value, "cemail");
            return (Criteria) this;
        }

        public Criteria andCemailGreaterThanOrEqualTo(String value) {
            addCriterion("cemail >=", value, "cemail");
            return (Criteria) this;
        }

        public Criteria andCemailLessThan(String value) {
            addCriterion("cemail <", value, "cemail");
            return (Criteria) this;
        }

        public Criteria andCemailLessThanOrEqualTo(String value) {
            addCriterion("cemail <=", value, "cemail");
            return (Criteria) this;
        }

        public Criteria andCemailLike(String value) {
            addCriterion("cemail like", value, "cemail");
            return (Criteria) this;
        }

        public Criteria andCemailNotLike(String value) {
            addCriterion("cemail not like", value, "cemail");
            return (Criteria) this;
        }

        public Criteria andCemailIn(List<String> values) {
            addCriterion("cemail in", values, "cemail");
            return (Criteria) this;
        }

        public Criteria andCemailNotIn(List<String> values) {
            addCriterion("cemail not in", values, "cemail");
            return (Criteria) this;
        }

        public Criteria andCemailBetween(String value1, String value2) {
            addCriterion("cemail between", value1, value2, "cemail");
            return (Criteria) this;
        }

        public Criteria andCemailNotBetween(String value1, String value2) {
            addCriterion("cemail not between", value1, value2, "cemail");
            return (Criteria) this;
        }

        public Criteria andCindustryIsNull() {
            addCriterion("cindustry is null");
            return (Criteria) this;
        }

        public Criteria andCindustryIsNotNull() {
            addCriterion("cindustry is not null");
            return (Criteria) this;
        }

        public Criteria andCindustryEqualTo(String value) {
            addCriterion("cindustry =", value, "cindustry");
            return (Criteria) this;
        }

        public Criteria andCindustryNotEqualTo(String value) {
            addCriterion("cindustry <>", value, "cindustry");
            return (Criteria) this;
        }

        public Criteria andCindustryGreaterThan(String value) {
            addCriterion("cindustry >", value, "cindustry");
            return (Criteria) this;
        }

        public Criteria andCindustryGreaterThanOrEqualTo(String value) {
            addCriterion("cindustry >=", value, "cindustry");
            return (Criteria) this;
        }

        public Criteria andCindustryLessThan(String value) {
            addCriterion("cindustry <", value, "cindustry");
            return (Criteria) this;
        }

        public Criteria andCindustryLessThanOrEqualTo(String value) {
            addCriterion("cindustry <=", value, "cindustry");
            return (Criteria) this;
        }

        public Criteria andCindustryLike(String value) {
            addCriterion("cindustry like", value, "cindustry");
            return (Criteria) this;
        }

        public Criteria andCindustryNotLike(String value) {
            addCriterion("cindustry not like", value, "cindustry");
            return (Criteria) this;
        }

        public Criteria andCindustryIn(List<String> values) {
            addCriterion("cindustry in", values, "cindustry");
            return (Criteria) this;
        }

        public Criteria andCindustryNotIn(List<String> values) {
            addCriterion("cindustry not in", values, "cindustry");
            return (Criteria) this;
        }

        public Criteria andCindustryBetween(String value1, String value2) {
            addCriterion("cindustry between", value1, value2, "cindustry");
            return (Criteria) this;
        }

        public Criteria andCindustryNotBetween(String value1, String value2) {
            addCriterion("cindustry not between", value1, value2, "cindustry");
            return (Criteria) this;
        }

        public Criteria andClevelIsNull() {
            addCriterion("clevel is null");
            return (Criteria) this;
        }

        public Criteria andClevelIsNotNull() {
            addCriterion("clevel is not null");
            return (Criteria) this;
        }

        public Criteria andClevelEqualTo(String value) {
            addCriterion("clevel =", value, "clevel");
            return (Criteria) this;
        }

        public Criteria andClevelNotEqualTo(String value) {
            addCriterion("clevel <>", value, "clevel");
            return (Criteria) this;
        }

        public Criteria andClevelGreaterThan(String value) {
            addCriterion("clevel >", value, "clevel");
            return (Criteria) this;
        }

        public Criteria andClevelGreaterThanOrEqualTo(String value) {
            addCriterion("clevel >=", value, "clevel");
            return (Criteria) this;
        }

        public Criteria andClevelLessThan(String value) {
            addCriterion("clevel <", value, "clevel");
            return (Criteria) this;
        }

        public Criteria andClevelLessThanOrEqualTo(String value) {
            addCriterion("clevel <=", value, "clevel");
            return (Criteria) this;
        }

        public Criteria andClevelLike(String value) {
            addCriterion("clevel like", value, "clevel");
            return (Criteria) this;
        }

        public Criteria andClevelNotLike(String value) {
            addCriterion("clevel not like", value, "clevel");
            return (Criteria) this;
        }

        public Criteria andClevelIn(List<String> values) {
            addCriterion("clevel in", values, "clevel");
            return (Criteria) this;
        }

        public Criteria andClevelNotIn(List<String> values) {
            addCriterion("clevel not in", values, "clevel");
            return (Criteria) this;
        }

        public Criteria andClevelBetween(String value1, String value2) {
            addCriterion("clevel between", value1, value2, "clevel");
            return (Criteria) this;
        }

        public Criteria andClevelNotBetween(String value1, String value2) {
            addCriterion("clevel not between", value1, value2, "clevel");
            return (Criteria) this;
        }

        public Criteria andCnexttimeIsNull() {
            addCriterion("cnextTime is null");
            return (Criteria) this;
        }

        public Criteria andCnexttimeIsNotNull() {
            addCriterion("cnextTime is not null");
            return (Criteria) this;
        }

        public Criteria andCnexttimeEqualTo(String value) {
            addCriterion("cnextTime =", value, "cnexttime");
            return (Criteria) this;
        }

        public Criteria andCnexttimeNotEqualTo(String value) {
            addCriterion("cnextTime <>", value, "cnexttime");
            return (Criteria) this;
        }

        public Criteria andCnexttimeGreaterThan(String value) {
            addCriterion("cnextTime >", value, "cnexttime");
            return (Criteria) this;
        }

        public Criteria andCnexttimeGreaterThanOrEqualTo(String value) {
            addCriterion("cnextTime >=", value, "cnexttime");
            return (Criteria) this;
        }

        public Criteria andCnexttimeLessThan(String value) {
            addCriterion("cnextTime <", value, "cnexttime");
            return (Criteria) this;
        }

        public Criteria andCnexttimeLessThanOrEqualTo(String value) {
            addCriterion("cnextTime <=", value, "cnexttime");
            return (Criteria) this;
        }

        public Criteria andCnexttimeLike(String value) {
            addCriterion("cnextTime like", value, "cnexttime");
            return (Criteria) this;
        }

        public Criteria andCnexttimeNotLike(String value) {
            addCriterion("cnextTime not like", value, "cnexttime");
            return (Criteria) this;
        }

        public Criteria andCnexttimeIn(List<String> values) {
            addCriterion("cnextTime in", values, "cnexttime");
            return (Criteria) this;
        }

        public Criteria andCnexttimeNotIn(List<String> values) {
            addCriterion("cnextTime not in", values, "cnexttime");
            return (Criteria) this;
        }

        public Criteria andCnexttimeBetween(String value1, String value2) {
            addCriterion("cnextTime between", value1, value2, "cnexttime");
            return (Criteria) this;
        }

        public Criteria andCnexttimeNotBetween(String value1, String value2) {
            addCriterion("cnextTime not between", value1, value2, "cnexttime");
            return (Criteria) this;
        }

        public Criteria andCtextIsNull() {
            addCriterion("ctext is null");
            return (Criteria) this;
        }

        public Criteria andCtextIsNotNull() {
            addCriterion("ctext is not null");
            return (Criteria) this;
        }

        public Criteria andCtextEqualTo(String value) {
            addCriterion("ctext =", value, "ctext");
            return (Criteria) this;
        }

        public Criteria andCtextNotEqualTo(String value) {
            addCriterion("ctext <>", value, "ctext");
            return (Criteria) this;
        }

        public Criteria andCtextGreaterThan(String value) {
            addCriterion("ctext >", value, "ctext");
            return (Criteria) this;
        }

        public Criteria andCtextGreaterThanOrEqualTo(String value) {
            addCriterion("ctext >=", value, "ctext");
            return (Criteria) this;
        }

        public Criteria andCtextLessThan(String value) {
            addCriterion("ctext <", value, "ctext");
            return (Criteria) this;
        }

        public Criteria andCtextLessThanOrEqualTo(String value) {
            addCriterion("ctext <=", value, "ctext");
            return (Criteria) this;
        }

        public Criteria andCtextLike(String value) {
            addCriterion("ctext like", value, "ctext");
            return (Criteria) this;
        }

        public Criteria andCtextNotLike(String value) {
            addCriterion("ctext not like", value, "ctext");
            return (Criteria) this;
        }

        public Criteria andCtextIn(List<String> values) {
            addCriterion("ctext in", values, "ctext");
            return (Criteria) this;
        }

        public Criteria andCtextNotIn(List<String> values) {
            addCriterion("ctext not in", values, "ctext");
            return (Criteria) this;
        }

        public Criteria andCtextBetween(String value1, String value2) {
            addCriterion("ctext between", value1, value2, "ctext");
            return (Criteria) this;
        }

        public Criteria andCtextNotBetween(String value1, String value2) {
            addCriterion("ctext not between", value1, value2, "ctext");
            return (Criteria) this;
        }

        public Criteria andCcityIsNull() {
            addCriterion("ccity is null");
            return (Criteria) this;
        }

        public Criteria andCcityIsNotNull() {
            addCriterion("ccity is not null");
            return (Criteria) this;
        }

        public Criteria andCcityEqualTo(String value) {
            addCriterion("ccity =", value, "ccity");
            return (Criteria) this;
        }

        public Criteria andCcityNotEqualTo(String value) {
            addCriterion("ccity <>", value, "ccity");
            return (Criteria) this;
        }

        public Criteria andCcityGreaterThan(String value) {
            addCriterion("ccity >", value, "ccity");
            return (Criteria) this;
        }

        public Criteria andCcityGreaterThanOrEqualTo(String value) {
            addCriterion("ccity >=", value, "ccity");
            return (Criteria) this;
        }

        public Criteria andCcityLessThan(String value) {
            addCriterion("ccity <", value, "ccity");
            return (Criteria) this;
        }

        public Criteria andCcityLessThanOrEqualTo(String value) {
            addCriterion("ccity <=", value, "ccity");
            return (Criteria) this;
        }

        public Criteria andCcityLike(String value) {
            addCriterion("ccity like", value, "ccity");
            return (Criteria) this;
        }

        public Criteria andCcityNotLike(String value) {
            addCriterion("ccity not like", value, "ccity");
            return (Criteria) this;
        }

        public Criteria andCcityIn(List<String> values) {
            addCriterion("ccity in", values, "ccity");
            return (Criteria) this;
        }

        public Criteria andCcityNotIn(List<String> values) {
            addCriterion("ccity not in", values, "ccity");
            return (Criteria) this;
        }

        public Criteria andCcityBetween(String value1, String value2) {
            addCriterion("ccity between", value1, value2, "ccity");
            return (Criteria) this;
        }

        public Criteria andCcityNotBetween(String value1, String value2) {
            addCriterion("ccity not between", value1, value2, "ccity");
            return (Criteria) this;
        }

        public Criteria andCdealIsNull() {
            addCriterion("cdeal is null");
            return (Criteria) this;
        }

        public Criteria andCdealIsNotNull() {
            addCriterion("cdeal is not null");
            return (Criteria) this;
        }

        public Criteria andCdealEqualTo(String value) {
            addCriterion("cdeal =", value, "cdeal");
            return (Criteria) this;
        }

        public Criteria andCdealNotEqualTo(String value) {
            addCriterion("cdeal <>", value, "cdeal");
            return (Criteria) this;
        }

        public Criteria andCdealGreaterThan(String value) {
            addCriterion("cdeal >", value, "cdeal");
            return (Criteria) this;
        }

        public Criteria andCdealGreaterThanOrEqualTo(String value) {
            addCriterion("cdeal >=", value, "cdeal");
            return (Criteria) this;
        }

        public Criteria andCdealLessThan(String value) {
            addCriterion("cdeal <", value, "cdeal");
            return (Criteria) this;
        }

        public Criteria andCdealLessThanOrEqualTo(String value) {
            addCriterion("cdeal <=", value, "cdeal");
            return (Criteria) this;
        }

        public Criteria andCdealLike(String value) {
            addCriterion("cdeal like", value, "cdeal");
            return (Criteria) this;
        }

        public Criteria andCdealNotLike(String value) {
            addCriterion("cdeal not like", value, "cdeal");
            return (Criteria) this;
        }

        public Criteria andCdealIn(List<String> values) {
            addCriterion("cdeal in", values, "cdeal");
            return (Criteria) this;
        }

        public Criteria andCdealNotIn(List<String> values) {
            addCriterion("cdeal not in", values, "cdeal");
            return (Criteria) this;
        }

        public Criteria andCdealBetween(String value1, String value2) {
            addCriterion("cdeal between", value1, value2, "cdeal");
            return (Criteria) this;
        }

        public Criteria andCdealNotBetween(String value1, String value2) {
            addCriterion("cdeal not between", value1, value2, "cdeal");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table client
     *
     * @mbg.generated do_not_delete_during_merge Wed Jan 06 15:32:23 CST 2021
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table client
     *
     * @mbg.generated Wed Jan 06 15:32:23 CST 2021
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}