package com.kakarote.crm9.erp.busniess.model;

public class Business {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column business.bid
     *
     * @mbg.generated Fri Jan 08 15:35:19 CST 2021
     */
    private Integer bid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column business.tid
     *
     * @mbg.generated Fri Jan 08 15:35:19 CST 2021
     */
    private Integer tid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column business.sid
     *
     * @mbg.generated Fri Jan 08 15:35:19 CST 2021
     */
    private Integer sid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column business.next_time
     *
     * @mbg.generated Fri Jan 08 15:35:19 CST 2021
     */
    private String nextTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column business.cid
     *
     * @mbg.generated Fri Jan 08 15:35:19 CST 2021
     */
    private Integer cid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column business.deal_date
     *
     * @mbg.generated Fri Jan 08 15:35:19 CST 2021
     */
    private String dealDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column business.bname
     *
     * @mbg.generated Fri Jan 08 15:35:19 CST 2021
     */
    private String bname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column business.money
     *
     * @mbg.generated Fri Jan 08 15:35:19 CST 2021
     */
    private String money;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column business.cjid
     *
     * @mbg.generated Fri Jan 08 15:35:19 CST 2021
     */
    private Integer cjid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column business.fzid
     *
     * @mbg.generated Fri Jan 08 15:35:19 CST 2021
     */
    private Integer fzid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column business.create_time
     *
     * @mbg.generated Fri Jan 08 15:35:19 CST 2021
     */
    private String createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column business.update_time
     *
     * @mbg.generated Fri Jan 08 15:35:19 CST 2021
     */
    private String updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column business.remark
     *
     * @mbg.generated Fri Jan 08 15:35:19 CST 2021
     */
    private String remark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column business.cpmoney
     *
     * @mbg.generated Fri Jan 08 15:35:19 CST 2021
     */
    private String cpmoney;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column business.discount_rate
     *
     * @mbg.generated Fri Jan 08 15:35:19 CST 2021
     */
    private String discountRate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column business.is_end
     *
     * @mbg.generated Fri Jan 08 15:35:19 CST 2021
     */
    private Integer isEnd;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column business.bid
     *
     * @return the value of business.bid
     *
     * @mbg.generated Fri Jan 08 15:35:19 CST 2021
     */
    public Integer getBid() {
        return bid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column business.bid
     *
     * @param bid the value for business.bid
     *
     * @mbg.generated Fri Jan 08 15:35:19 CST 2021
     */
    public void setBid(Integer bid) {
        this.bid = bid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column business.tid
     *
     * @return the value of business.tid
     *
     * @mbg.generated Fri Jan 08 15:35:19 CST 2021
     */
    public Integer getTid() {
        return tid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column business.tid
     *
     * @param tid the value for business.tid
     *
     * @mbg.generated Fri Jan 08 15:35:19 CST 2021
     */
    public void setTid(Integer tid) {
        this.tid = tid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column business.sid
     *
     * @return the value of business.sid
     *
     * @mbg.generated Fri Jan 08 15:35:19 CST 2021
     */
    public Integer getSid() {
        return sid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column business.sid
     *
     * @param sid the value for business.sid
     *
     * @mbg.generated Fri Jan 08 15:35:19 CST 2021
     */
    public void setSid(Integer sid) {
        this.sid = sid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column business.next_time
     *
     * @return the value of business.next_time
     *
     * @mbg.generated Fri Jan 08 15:35:19 CST 2021
     */
    public String getNextTime() {
        return nextTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column business.next_time
     *
     * @param nextTime the value for business.next_time
     *
     * @mbg.generated Fri Jan 08 15:35:19 CST 2021
     */
    public void setNextTime(String nextTime) {
        this.nextTime = nextTime == null ? null : nextTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column business.cid
     *
     * @return the value of business.cid
     *
     * @mbg.generated Fri Jan 08 15:35:19 CST 2021
     */
    public Integer getCid() {
        return cid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column business.cid
     *
     * @param cid the value for business.cid
     *
     * @mbg.generated Fri Jan 08 15:35:19 CST 2021
     */
    public void setCid(Integer cid) {
        this.cid = cid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column business.deal_date
     *
     * @return the value of business.deal_date
     *
     * @mbg.generated Fri Jan 08 15:35:19 CST 2021
     */
    public String getDealDate() {
        return dealDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column business.deal_date
     *
     * @param dealDate the value for business.deal_date
     *
     * @mbg.generated Fri Jan 08 15:35:19 CST 2021
     */
    public void setDealDate(String dealDate) {
        this.dealDate = dealDate == null ? null : dealDate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column business.bname
     *
     * @return the value of business.bname
     *
     * @mbg.generated Fri Jan 08 15:35:19 CST 2021
     */
    public String getBname() {
        return bname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column business.bname
     *
     * @param bname the value for business.bname
     *
     * @mbg.generated Fri Jan 08 15:35:19 CST 2021
     */
    public void setBname(String bname) {
        this.bname = bname == null ? null : bname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column business.money
     *
     * @return the value of business.money
     *
     * @mbg.generated Fri Jan 08 15:35:19 CST 2021
     */
    public String getMoney() {
        return money;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column business.money
     *
     * @param money the value for business.money
     *
     * @mbg.generated Fri Jan 08 15:35:19 CST 2021
     */
    public void setMoney(String money) {
        this.money = money == null ? null : money.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column business.cjid
     *
     * @return the value of business.cjid
     *
     * @mbg.generated Fri Jan 08 15:35:19 CST 2021
     */
    public Integer getCjid() {
        return cjid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column business.cjid
     *
     * @param cjid the value for business.cjid
     *
     * @mbg.generated Fri Jan 08 15:35:19 CST 2021
     */
    public void setCjid(Integer cjid) {
        this.cjid = cjid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column business.fzid
     *
     * @return the value of business.fzid
     *
     * @mbg.generated Fri Jan 08 15:35:19 CST 2021
     */
    public Integer getFzid() {
        return fzid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column business.fzid
     *
     * @param fzid the value for business.fzid
     *
     * @mbg.generated Fri Jan 08 15:35:19 CST 2021
     */
    public void setFzid(Integer fzid) {
        this.fzid = fzid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column business.create_time
     *
     * @return the value of business.create_time
     *
     * @mbg.generated Fri Jan 08 15:35:19 CST 2021
     */
    public String getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column business.create_time
     *
     * @param createTime the value for business.create_time
     *
     * @mbg.generated Fri Jan 08 15:35:19 CST 2021
     */
    public void setCreateTime(String createTime) {
        this.createTime = createTime == null ? null : createTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column business.update_time
     *
     * @return the value of business.update_time
     *
     * @mbg.generated Fri Jan 08 15:35:19 CST 2021
     */
    public String getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column business.update_time
     *
     * @param updateTime the value for business.update_time
     *
     * @mbg.generated Fri Jan 08 15:35:19 CST 2021
     */
    public void setUpdateTime(String updateTime) {
        this.updateTime = updateTime == null ? null : updateTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column business.remark
     *
     * @return the value of business.remark
     *
     * @mbg.generated Fri Jan 08 15:35:19 CST 2021
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column business.remark
     *
     * @param remark the value for business.remark
     *
     * @mbg.generated Fri Jan 08 15:35:19 CST 2021
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column business.cpmoney
     *
     * @return the value of business.cpmoney
     *
     * @mbg.generated Fri Jan 08 15:35:19 CST 2021
     */
    public String getCpmoney() {
        return cpmoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column business.cpmoney
     *
     * @param cpmoney the value for business.cpmoney
     *
     * @mbg.generated Fri Jan 08 15:35:19 CST 2021
     */
    public void setCpmoney(String cpmoney) {
        this.cpmoney = cpmoney == null ? null : cpmoney.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column business.discount_rate
     *
     * @return the value of business.discount_rate
     *
     * @mbg.generated Fri Jan 08 15:35:19 CST 2021
     */
    public String getDiscountRate() {
        return discountRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column business.discount_rate
     *
     * @param discountRate the value for business.discount_rate
     *
     * @mbg.generated Fri Jan 08 15:35:19 CST 2021
     */
    public void setDiscountRate(String discountRate) {
        this.discountRate = discountRate == null ? null : discountRate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column business.is_end
     *
     * @return the value of business.is_end
     *
     * @mbg.generated Fri Jan 08 15:35:19 CST 2021
     */
    public Integer getIsEnd() {
        return isEnd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column business.is_end
     *
     * @param isEnd the value for business.is_end
     *
     * @mbg.generated Fri Jan 08 15:35:19 CST 2021
     */
    public void setIsEnd(Integer isEnd) {
        this.isEnd = isEnd;
    }
}