package com.kakarote.crm9.erp.busniess.model;

public class BusinessChange {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column business_change.change_id
     *
     * @mbg.generated Fri Jan 08 15:35:19 CST 2021
     */
    private Integer changeId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column business_change.bid
     *
     * @mbg.generated Fri Jan 08 15:35:19 CST 2021
     */
    private Integer bid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column business_change.sid
     *
     * @mbg.generated Fri Jan 08 15:35:19 CST 2021
     */
    private Integer sid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column business_change.create_time
     *
     * @mbg.generated Fri Jan 08 15:35:19 CST 2021
     */
    private String createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column business_change.cjid
     *
     * @mbg.generated Fri Jan 08 15:35:19 CST 2021
     */
    private Integer cjid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column business_change.change_id
     *
     * @return the value of business_change.change_id
     *
     * @mbg.generated Fri Jan 08 15:35:19 CST 2021
     */
    public Integer getChangeId() {
        return changeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column business_change.change_id
     *
     * @param changeId the value for business_change.change_id
     *
     * @mbg.generated Fri Jan 08 15:35:19 CST 2021
     */
    public void setChangeId(Integer changeId) {
        this.changeId = changeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column business_change.bid
     *
     * @return the value of business_change.bid
     *
     * @mbg.generated Fri Jan 08 15:35:19 CST 2021
     */
    public Integer getBid() {
        return bid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column business_change.bid
     *
     * @param bid the value for business_change.bid
     *
     * @mbg.generated Fri Jan 08 15:35:19 CST 2021
     */
    public void setBid(Integer bid) {
        this.bid = bid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column business_change.sid
     *
     * @return the value of business_change.sid
     *
     * @mbg.generated Fri Jan 08 15:35:19 CST 2021
     */
    public Integer getSid() {
        return sid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column business_change.sid
     *
     * @param sid the value for business_change.sid
     *
     * @mbg.generated Fri Jan 08 15:35:19 CST 2021
     */
    public void setSid(Integer sid) {
        this.sid = sid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column business_change.create_time
     *
     * @return the value of business_change.create_time
     *
     * @mbg.generated Fri Jan 08 15:35:19 CST 2021
     */
    public String getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column business_change.create_time
     *
     * @param createTime the value for business_change.create_time
     *
     * @mbg.generated Fri Jan 08 15:35:19 CST 2021
     */
    public void setCreateTime(String createTime) {
        this.createTime = createTime == null ? null : createTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column business_change.cjid
     *
     * @return the value of business_change.cjid
     *
     * @mbg.generated Fri Jan 08 15:35:19 CST 2021
     */
    public Integer getCjid() {
        return cjid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column business_change.cjid
     *
     * @param cjid the value for business_change.cjid
     *
     * @mbg.generated Fri Jan 08 15:35:19 CST 2021
     */
    public void setCjid(Integer cjid) {
        this.cjid = cjid;
    }
}