package com.kakarote.crm9.erp.busniess.model;

public class ContactsBusiness {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column contacts_business.id
     *
     * @mbg.generated Thu Jan 07 02:25:16 CST 2021
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column contacts_business.bid
     *
     * @mbg.generated Thu Jan 07 02:25:16 CST 2021
     */
    private Integer bid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column contacts_business.contact_id
     *
     * @mbg.generated Thu Jan 07 02:25:16 CST 2021
     */
    private Integer contactId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column contacts_business.id
     *
     * @return the value of contacts_business.id
     *
     * @mbg.generated Thu Jan 07 02:25:16 CST 2021
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column contacts_business.id
     *
     * @param id the value for contacts_business.id
     *
     * @mbg.generated Thu Jan 07 02:25:16 CST 2021
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column contacts_business.bid
     *
     * @return the value of contacts_business.bid
     *
     * @mbg.generated Thu Jan 07 02:25:16 CST 2021
     */
    public Integer getBid() {
        return bid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column contacts_business.bid
     *
     * @param bid the value for contacts_business.bid
     *
     * @mbg.generated Thu Jan 07 02:25:16 CST 2021
     */
    public void setBid(Integer bid) {
        this.bid = bid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column contacts_business.contact_id
     *
     * @return the value of contacts_business.contact_id
     *
     * @mbg.generated Thu Jan 07 02:25:16 CST 2021
     */
    public Integer getContactId() {
        return contactId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column contacts_business.contact_id
     *
     * @param contactId the value for contacts_business.contact_id
     *
     * @mbg.generated Thu Jan 07 02:25:16 CST 2021
     */
    public void setContactId(Integer contactId) {
        this.contactId = contactId;
    }
}