package com.kakarote.crm9.erp.client.model;

public class Client {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column client.cid
     *
     * @mbg.generated Wed Jan 06 15:32:23 CST 2021
     */
    private Integer cid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column client.cname
     *
     * @mbg.generated Wed Jan 06 15:32:23 CST 2021
     */
    private String cname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column client.csource
     *
     * @mbg.generated Wed Jan 06 15:32:23 CST 2021
     */
    private String csource;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column client.ctel
     *
     * @mbg.generated Wed Jan 06 15:32:23 CST 2021
     */
    private String ctel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column client.ccall
     *
     * @mbg.generated Wed Jan 06 15:32:23 CST 2021
     */
    private String ccall;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column client.cweb
     *
     * @mbg.generated Wed Jan 06 15:32:23 CST 2021
     */
    private String cweb;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column client.cemail
     *
     * @mbg.generated Wed Jan 06 15:32:23 CST 2021
     */
    private String cemail;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column client.cindustry
     *
     * @mbg.generated Wed Jan 06 15:32:23 CST 2021
     */
    private String cindustry;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column client.clevel
     *
     * @mbg.generated Wed Jan 06 15:32:23 CST 2021
     */
    private String clevel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column client.cnextTime
     *
     * @mbg.generated Wed Jan 06 15:32:23 CST 2021
     */
    private String cnexttime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column client.ctext
     *
     * @mbg.generated Wed Jan 06 15:32:23 CST 2021
     */
    private String ctext;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column client.ccity
     *
     * @mbg.generated Wed Jan 06 15:32:23 CST 2021
     */
    private String ccity;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column client.cdeal
     *
     * @mbg.generated Wed Jan 06 15:32:23 CST 2021
     */
    private String cdeal;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column client.cid
     *
     * @return the value of client.cid
     *
     * @mbg.generated Wed Jan 06 15:32:23 CST 2021
     */
    public Integer getCid() {
        return cid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column client.cid
     *
     * @param cid the value for client.cid
     *
     * @mbg.generated Wed Jan 06 15:32:23 CST 2021
     */
    public void setCid(Integer cid) {
        this.cid = cid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column client.cname
     *
     * @return the value of client.cname
     *
     * @mbg.generated Wed Jan 06 15:32:23 CST 2021
     */
    public String getCname() {
        return cname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column client.cname
     *
     * @param cname the value for client.cname
     *
     * @mbg.generated Wed Jan 06 15:32:23 CST 2021
     */
    public void setCname(String cname) {
        this.cname = cname == null ? null : cname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column client.csource
     *
     * @return the value of client.csource
     *
     * @mbg.generated Wed Jan 06 15:32:23 CST 2021
     */
    public String getCsource() {
        return csource;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column client.csource
     *
     * @param csource the value for client.csource
     *
     * @mbg.generated Wed Jan 06 15:32:23 CST 2021
     */
    public void setCsource(String csource) {
        this.csource = csource == null ? null : csource.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column client.ctel
     *
     * @return the value of client.ctel
     *
     * @mbg.generated Wed Jan 06 15:32:23 CST 2021
     */
    public String getCtel() {
        return ctel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column client.ctel
     *
     * @param ctel the value for client.ctel
     *
     * @mbg.generated Wed Jan 06 15:32:23 CST 2021
     */
    public void setCtel(String ctel) {
        this.ctel = ctel == null ? null : ctel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column client.ccall
     *
     * @return the value of client.ccall
     *
     * @mbg.generated Wed Jan 06 15:32:23 CST 2021
     */
    public String getCcall() {
        return ccall;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column client.ccall
     *
     * @param ccall the value for client.ccall
     *
     * @mbg.generated Wed Jan 06 15:32:23 CST 2021
     */
    public void setCcall(String ccall) {
        this.ccall = ccall == null ? null : ccall.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column client.cweb
     *
     * @return the value of client.cweb
     *
     * @mbg.generated Wed Jan 06 15:32:23 CST 2021
     */
    public String getCweb() {
        return cweb;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column client.cweb
     *
     * @param cweb the value for client.cweb
     *
     * @mbg.generated Wed Jan 06 15:32:23 CST 2021
     */
    public void setCweb(String cweb) {
        this.cweb = cweb == null ? null : cweb.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column client.cemail
     *
     * @return the value of client.cemail
     *
     * @mbg.generated Wed Jan 06 15:32:23 CST 2021
     */
    public String getCemail() {
        return cemail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column client.cemail
     *
     * @param cemail the value for client.cemail
     *
     * @mbg.generated Wed Jan 06 15:32:23 CST 2021
     */
    public void setCemail(String cemail) {
        this.cemail = cemail == null ? null : cemail.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column client.cindustry
     *
     * @return the value of client.cindustry
     *
     * @mbg.generated Wed Jan 06 15:32:23 CST 2021
     */
    public String getCindustry() {
        return cindustry;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column client.cindustry
     *
     * @param cindustry the value for client.cindustry
     *
     * @mbg.generated Wed Jan 06 15:32:23 CST 2021
     */
    public void setCindustry(String cindustry) {
        this.cindustry = cindustry == null ? null : cindustry.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column client.clevel
     *
     * @return the value of client.clevel
     *
     * @mbg.generated Wed Jan 06 15:32:23 CST 2021
     */
    public String getClevel() {
        return clevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column client.clevel
     *
     * @param clevel the value for client.clevel
     *
     * @mbg.generated Wed Jan 06 15:32:23 CST 2021
     */
    public void setClevel(String clevel) {
        this.clevel = clevel == null ? null : clevel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column client.cnextTime
     *
     * @return the value of client.cnextTime
     *
     * @mbg.generated Wed Jan 06 15:32:23 CST 2021
     */
    public String getCnexttime() {
        return cnexttime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column client.cnextTime
     *
     * @param cnexttime the value for client.cnextTime
     *
     * @mbg.generated Wed Jan 06 15:32:23 CST 2021
     */
    public void setCnexttime(String cnexttime) {
        this.cnexttime = cnexttime == null ? null : cnexttime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column client.ctext
     *
     * @return the value of client.ctext
     *
     * @mbg.generated Wed Jan 06 15:32:23 CST 2021
     */
    public String getCtext() {
        return ctext;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column client.ctext
     *
     * @param ctext the value for client.ctext
     *
     * @mbg.generated Wed Jan 06 15:32:23 CST 2021
     */
    public void setCtext(String ctext) {
        this.ctext = ctext == null ? null : ctext.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column client.ccity
     *
     * @return the value of client.ccity
     *
     * @mbg.generated Wed Jan 06 15:32:23 CST 2021
     */
    public String getCcity() {
        return ccity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column client.ccity
     *
     * @param ccity the value for client.ccity
     *
     * @mbg.generated Wed Jan 06 15:32:23 CST 2021
     */
    public void setCcity(String ccity) {
        this.ccity = ccity == null ? null : ccity.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column client.cdeal
     *
     * @return the value of client.cdeal
     *
     * @mbg.generated Wed Jan 06 15:32:23 CST 2021
     */
    public String getCdeal() {
        return cdeal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column client.cdeal
     *
     * @param cdeal the value for client.cdeal
     *
     * @mbg.generated Wed Jan 06 15:32:23 CST 2021
     */
    public void setCdeal(String cdeal) {
        this.cdeal = cdeal == null ? null : cdeal.trim();
    }
}