package com.kakarote.crm9.erp.chanpin.model;

public class Product {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.proid
     *
     * @mbg.generated Thu Jan 07 02:14:27 CST 2021
     */
    private Integer proid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.price
     *
     * @mbg.generated Thu Jan 07 02:14:27 CST 2021
     */
    private String price;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.creat_user_id
     *
     * @mbg.generated Thu Jan 07 02:14:27 CST 2021
     */
    private Integer creatUserId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.owner_user_id
     *
     * @mbg.generated Thu Jan 07 02:14:27 CST 2021
     */
    private Integer ownerUserId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.proname
     *
     * @mbg.generated Thu Jan 07 02:14:27 CST 2021
     */
    private String proname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.pronum
     *
     * @mbg.generated Thu Jan 07 02:14:27 CST 2021
     */
    private String pronum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.prostatus
     *
     * @mbg.generated Thu Jan 07 02:14:27 CST 2021
     */
    private Integer prostatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.procreatetime
     *
     * @mbg.generated Thu Jan 07 02:14:27 CST 2021
     */
    private String procreatetime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.prounit
     *
     * @mbg.generated Thu Jan 07 02:14:27 CST 2021
     */
    private String prounit;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.category_id
     *
     * @mbg.generated Thu Jan 07 02:14:27 CST 2021
     */
    private Integer categoryId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.discription
     *
     * @mbg.generated Thu Jan 07 02:14:27 CST 2021
     */
    private String discription;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.proid
     *
     * @return the value of product.proid
     *
     * @mbg.generated Thu Jan 07 02:14:27 CST 2021
     */
    public Integer getProid() {
        return proid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.proid
     *
     * @param proid the value for product.proid
     *
     * @mbg.generated Thu Jan 07 02:14:27 CST 2021
     */
    public void setProid(Integer proid) {
        this.proid = proid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.price
     *
     * @return the value of product.price
     *
     * @mbg.generated Thu Jan 07 02:14:27 CST 2021
     */
    public String getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.price
     *
     * @param price the value for product.price
     *
     * @mbg.generated Thu Jan 07 02:14:27 CST 2021
     */
    public void setPrice(String price) {
        this.price = price == null ? null : price.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.creat_user_id
     *
     * @return the value of product.creat_user_id
     *
     * @mbg.generated Thu Jan 07 02:14:27 CST 2021
     */
    public Integer getCreatUserId() {
        return creatUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.creat_user_id
     *
     * @param creatUserId the value for product.creat_user_id
     *
     * @mbg.generated Thu Jan 07 02:14:27 CST 2021
     */
    public void setCreatUserId(Integer creatUserId) {
        this.creatUserId = creatUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.owner_user_id
     *
     * @return the value of product.owner_user_id
     *
     * @mbg.generated Thu Jan 07 02:14:27 CST 2021
     */
    public Integer getOwnerUserId() {
        return ownerUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.owner_user_id
     *
     * @param ownerUserId the value for product.owner_user_id
     *
     * @mbg.generated Thu Jan 07 02:14:27 CST 2021
     */
    public void setOwnerUserId(Integer ownerUserId) {
        this.ownerUserId = ownerUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.proname
     *
     * @return the value of product.proname
     *
     * @mbg.generated Thu Jan 07 02:14:27 CST 2021
     */
    public String getProname() {
        return proname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.proname
     *
     * @param proname the value for product.proname
     *
     * @mbg.generated Thu Jan 07 02:14:27 CST 2021
     */
    public void setProname(String proname) {
        this.proname = proname == null ? null : proname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.pronum
     *
     * @return the value of product.pronum
     *
     * @mbg.generated Thu Jan 07 02:14:27 CST 2021
     */
    public String getPronum() {
        return pronum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.pronum
     *
     * @param pronum the value for product.pronum
     *
     * @mbg.generated Thu Jan 07 02:14:27 CST 2021
     */
    public void setPronum(String pronum) {
        this.pronum = pronum == null ? null : pronum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.prostatus
     *
     * @return the value of product.prostatus
     *
     * @mbg.generated Thu Jan 07 02:14:27 CST 2021
     */
    public Integer getProstatus() {
        return prostatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.prostatus
     *
     * @param prostatus the value for product.prostatus
     *
     * @mbg.generated Thu Jan 07 02:14:27 CST 2021
     */
    public void setProstatus(Integer prostatus) {
        this.prostatus = prostatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.procreatetime
     *
     * @return the value of product.procreatetime
     *
     * @mbg.generated Thu Jan 07 02:14:27 CST 2021
     */
    public String getProcreatetime() {
        return procreatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.procreatetime
     *
     * @param procreatetime the value for product.procreatetime
     *
     * @mbg.generated Thu Jan 07 02:14:27 CST 2021
     */
    public void setProcreatetime(String procreatetime) {
        this.procreatetime = procreatetime == null ? null : procreatetime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.prounit
     *
     * @return the value of product.prounit
     *
     * @mbg.generated Thu Jan 07 02:14:27 CST 2021
     */
    public String getProunit() {
        return prounit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.prounit
     *
     * @param prounit the value for product.prounit
     *
     * @mbg.generated Thu Jan 07 02:14:27 CST 2021
     */
    public void setProunit(String prounit) {
        this.prounit = prounit == null ? null : prounit.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.category_id
     *
     * @return the value of product.category_id
     *
     * @mbg.generated Thu Jan 07 02:14:27 CST 2021
     */
    public Integer getCategoryId() {
        return categoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.category_id
     *
     * @param categoryId the value for product.category_id
     *
     * @mbg.generated Thu Jan 07 02:14:27 CST 2021
     */
    public void setCategoryId(Integer categoryId) {
        this.categoryId = categoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.discription
     *
     * @return the value of product.discription
     *
     * @mbg.generated Thu Jan 07 02:14:27 CST 2021
     */
    public String getDiscription() {
        return discription;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.discription
     *
     * @param discription the value for product.discription
     *
     * @mbg.generated Thu Jan 07 02:14:27 CST 2021
     */
    public void setDiscription(String discription) {
        this.discription = discription == null ? null : discription.trim();
    }
}