package com.kakarote.crm9.erp.chanpin.model;

import java.util.ArrayList;
import java.util.List;

public class ProductExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table product
     *
     * @mbg.generated Thu Jan 07 02:14:27 CST 2021
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table product
     *
     * @mbg.generated Thu Jan 07 02:14:27 CST 2021
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table product
     *
     * @mbg.generated Thu Jan 07 02:14:27 CST 2021
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product
     *
     * @mbg.generated Thu Jan 07 02:14:27 CST 2021
     */
    public ProductExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product
     *
     * @mbg.generated Thu Jan 07 02:14:27 CST 2021
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product
     *
     * @mbg.generated Thu Jan 07 02:14:27 CST 2021
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product
     *
     * @mbg.generated Thu Jan 07 02:14:27 CST 2021
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product
     *
     * @mbg.generated Thu Jan 07 02:14:27 CST 2021
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product
     *
     * @mbg.generated Thu Jan 07 02:14:27 CST 2021
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product
     *
     * @mbg.generated Thu Jan 07 02:14:27 CST 2021
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product
     *
     * @mbg.generated Thu Jan 07 02:14:27 CST 2021
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product
     *
     * @mbg.generated Thu Jan 07 02:14:27 CST 2021
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product
     *
     * @mbg.generated Thu Jan 07 02:14:27 CST 2021
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product
     *
     * @mbg.generated Thu Jan 07 02:14:27 CST 2021
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table product
     *
     * @mbg.generated Thu Jan 07 02:14:27 CST 2021
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andProidIsNull() {
            addCriterion("proid is null");
            return (Criteria) this;
        }

        public Criteria andProidIsNotNull() {
            addCriterion("proid is not null");
            return (Criteria) this;
        }

        public Criteria andProidEqualTo(Integer value) {
            addCriterion("proid =", value, "proid");
            return (Criteria) this;
        }

        public Criteria andProidNotEqualTo(Integer value) {
            addCriterion("proid <>", value, "proid");
            return (Criteria) this;
        }

        public Criteria andProidGreaterThan(Integer value) {
            addCriterion("proid >", value, "proid");
            return (Criteria) this;
        }

        public Criteria andProidGreaterThanOrEqualTo(Integer value) {
            addCriterion("proid >=", value, "proid");
            return (Criteria) this;
        }

        public Criteria andProidLessThan(Integer value) {
            addCriterion("proid <", value, "proid");
            return (Criteria) this;
        }

        public Criteria andProidLessThanOrEqualTo(Integer value) {
            addCriterion("proid <=", value, "proid");
            return (Criteria) this;
        }

        public Criteria andProidIn(List<Integer> values) {
            addCriterion("proid in", values, "proid");
            return (Criteria) this;
        }

        public Criteria andProidNotIn(List<Integer> values) {
            addCriterion("proid not in", values, "proid");
            return (Criteria) this;
        }

        public Criteria andProidBetween(Integer value1, Integer value2) {
            addCriterion("proid between", value1, value2, "proid");
            return (Criteria) this;
        }

        public Criteria andProidNotBetween(Integer value1, Integer value2) {
            addCriterion("proid not between", value1, value2, "proid");
            return (Criteria) this;
        }

        public Criteria andPriceIsNull() {
            addCriterion("price is null");
            return (Criteria) this;
        }

        public Criteria andPriceIsNotNull() {
            addCriterion("price is not null");
            return (Criteria) this;
        }

        public Criteria andPriceEqualTo(String value) {
            addCriterion("price =", value, "price");
            return (Criteria) this;
        }

        public Criteria andPriceNotEqualTo(String value) {
            addCriterion("price <>", value, "price");
            return (Criteria) this;
        }

        public Criteria andPriceGreaterThan(String value) {
            addCriterion("price >", value, "price");
            return (Criteria) this;
        }

        public Criteria andPriceGreaterThanOrEqualTo(String value) {
            addCriterion("price >=", value, "price");
            return (Criteria) this;
        }

        public Criteria andPriceLessThan(String value) {
            addCriterion("price <", value, "price");
            return (Criteria) this;
        }

        public Criteria andPriceLessThanOrEqualTo(String value) {
            addCriterion("price <=", value, "price");
            return (Criteria) this;
        }

        public Criteria andPriceLike(String value) {
            addCriterion("price like", value, "price");
            return (Criteria) this;
        }

        public Criteria andPriceNotLike(String value) {
            addCriterion("price not like", value, "price");
            return (Criteria) this;
        }

        public Criteria andPriceIn(List<String> values) {
            addCriterion("price in", values, "price");
            return (Criteria) this;
        }

        public Criteria andPriceNotIn(List<String> values) {
            addCriterion("price not in", values, "price");
            return (Criteria) this;
        }

        public Criteria andPriceBetween(String value1, String value2) {
            addCriterion("price between", value1, value2, "price");
            return (Criteria) this;
        }

        public Criteria andPriceNotBetween(String value1, String value2) {
            addCriterion("price not between", value1, value2, "price");
            return (Criteria) this;
        }

        public Criteria andCreatUserIdIsNull() {
            addCriterion("creat_user_id is null");
            return (Criteria) this;
        }

        public Criteria andCreatUserIdIsNotNull() {
            addCriterion("creat_user_id is not null");
            return (Criteria) this;
        }

        public Criteria andCreatUserIdEqualTo(Integer value) {
            addCriterion("creat_user_id =", value, "creatUserId");
            return (Criteria) this;
        }

        public Criteria andCreatUserIdNotEqualTo(Integer value) {
            addCriterion("creat_user_id <>", value, "creatUserId");
            return (Criteria) this;
        }

        public Criteria andCreatUserIdGreaterThan(Integer value) {
            addCriterion("creat_user_id >", value, "creatUserId");
            return (Criteria) this;
        }

        public Criteria andCreatUserIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("creat_user_id >=", value, "creatUserId");
            return (Criteria) this;
        }

        public Criteria andCreatUserIdLessThan(Integer value) {
            addCriterion("creat_user_id <", value, "creatUserId");
            return (Criteria) this;
        }

        public Criteria andCreatUserIdLessThanOrEqualTo(Integer value) {
            addCriterion("creat_user_id <=", value, "creatUserId");
            return (Criteria) this;
        }

        public Criteria andCreatUserIdIn(List<Integer> values) {
            addCriterion("creat_user_id in", values, "creatUserId");
            return (Criteria) this;
        }

        public Criteria andCreatUserIdNotIn(List<Integer> values) {
            addCriterion("creat_user_id not in", values, "creatUserId");
            return (Criteria) this;
        }

        public Criteria andCreatUserIdBetween(Integer value1, Integer value2) {
            addCriterion("creat_user_id between", value1, value2, "creatUserId");
            return (Criteria) this;
        }

        public Criteria andCreatUserIdNotBetween(Integer value1, Integer value2) {
            addCriterion("creat_user_id not between", value1, value2, "creatUserId");
            return (Criteria) this;
        }

        public Criteria andOwnerUserIdIsNull() {
            addCriterion("owner_user_id is null");
            return (Criteria) this;
        }

        public Criteria andOwnerUserIdIsNotNull() {
            addCriterion("owner_user_id is not null");
            return (Criteria) this;
        }

        public Criteria andOwnerUserIdEqualTo(Integer value) {
            addCriterion("owner_user_id =", value, "ownerUserId");
            return (Criteria) this;
        }

        public Criteria andOwnerUserIdNotEqualTo(Integer value) {
            addCriterion("owner_user_id <>", value, "ownerUserId");
            return (Criteria) this;
        }

        public Criteria andOwnerUserIdGreaterThan(Integer value) {
            addCriterion("owner_user_id >", value, "ownerUserId");
            return (Criteria) this;
        }

        public Criteria andOwnerUserIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("owner_user_id >=", value, "ownerUserId");
            return (Criteria) this;
        }

        public Criteria andOwnerUserIdLessThan(Integer value) {
            addCriterion("owner_user_id <", value, "ownerUserId");
            return (Criteria) this;
        }

        public Criteria andOwnerUserIdLessThanOrEqualTo(Integer value) {
            addCriterion("owner_user_id <=", value, "ownerUserId");
            return (Criteria) this;
        }

        public Criteria andOwnerUserIdIn(List<Integer> values) {
            addCriterion("owner_user_id in", values, "ownerUserId");
            return (Criteria) this;
        }

        public Criteria andOwnerUserIdNotIn(List<Integer> values) {
            addCriterion("owner_user_id not in", values, "ownerUserId");
            return (Criteria) this;
        }

        public Criteria andOwnerUserIdBetween(Integer value1, Integer value2) {
            addCriterion("owner_user_id between", value1, value2, "ownerUserId");
            return (Criteria) this;
        }

        public Criteria andOwnerUserIdNotBetween(Integer value1, Integer value2) {
            addCriterion("owner_user_id not between", value1, value2, "ownerUserId");
            return (Criteria) this;
        }

        public Criteria andPronameIsNull() {
            addCriterion("proname is null");
            return (Criteria) this;
        }

        public Criteria andPronameIsNotNull() {
            addCriterion("proname is not null");
            return (Criteria) this;
        }

        public Criteria andPronameEqualTo(String value) {
            addCriterion("proname =", value, "proname");
            return (Criteria) this;
        }

        public Criteria andPronameNotEqualTo(String value) {
            addCriterion("proname <>", value, "proname");
            return (Criteria) this;
        }

        public Criteria andPronameGreaterThan(String value) {
            addCriterion("proname >", value, "proname");
            return (Criteria) this;
        }

        public Criteria andPronameGreaterThanOrEqualTo(String value) {
            addCriterion("proname >=", value, "proname");
            return (Criteria) this;
        }

        public Criteria andPronameLessThan(String value) {
            addCriterion("proname <", value, "proname");
            return (Criteria) this;
        }

        public Criteria andPronameLessThanOrEqualTo(String value) {
            addCriterion("proname <=", value, "proname");
            return (Criteria) this;
        }

        public Criteria andPronameLike(String value) {
            addCriterion("proname like", value, "proname");
            return (Criteria) this;
        }

        public Criteria andPronameNotLike(String value) {
            addCriterion("proname not like", value, "proname");
            return (Criteria) this;
        }

        public Criteria andPronameIn(List<String> values) {
            addCriterion("proname in", values, "proname");
            return (Criteria) this;
        }

        public Criteria andPronameNotIn(List<String> values) {
            addCriterion("proname not in", values, "proname");
            return (Criteria) this;
        }

        public Criteria andPronameBetween(String value1, String value2) {
            addCriterion("proname between", value1, value2, "proname");
            return (Criteria) this;
        }

        public Criteria andPronameNotBetween(String value1, String value2) {
            addCriterion("proname not between", value1, value2, "proname");
            return (Criteria) this;
        }

        public Criteria andPronumIsNull() {
            addCriterion("pronum is null");
            return (Criteria) this;
        }

        public Criteria andPronumIsNotNull() {
            addCriterion("pronum is not null");
            return (Criteria) this;
        }

        public Criteria andPronumEqualTo(String value) {
            addCriterion("pronum =", value, "pronum");
            return (Criteria) this;
        }

        public Criteria andPronumNotEqualTo(String value) {
            addCriterion("pronum <>", value, "pronum");
            return (Criteria) this;
        }

        public Criteria andPronumGreaterThan(String value) {
            addCriterion("pronum >", value, "pronum");
            return (Criteria) this;
        }

        public Criteria andPronumGreaterThanOrEqualTo(String value) {
            addCriterion("pronum >=", value, "pronum");
            return (Criteria) this;
        }

        public Criteria andPronumLessThan(String value) {
            addCriterion("pronum <", value, "pronum");
            return (Criteria) this;
        }

        public Criteria andPronumLessThanOrEqualTo(String value) {
            addCriterion("pronum <=", value, "pronum");
            return (Criteria) this;
        }

        public Criteria andPronumLike(String value) {
            addCriterion("pronum like", value, "pronum");
            return (Criteria) this;
        }

        public Criteria andPronumNotLike(String value) {
            addCriterion("pronum not like", value, "pronum");
            return (Criteria) this;
        }

        public Criteria andPronumIn(List<String> values) {
            addCriterion("pronum in", values, "pronum");
            return (Criteria) this;
        }

        public Criteria andPronumNotIn(List<String> values) {
            addCriterion("pronum not in", values, "pronum");
            return (Criteria) this;
        }

        public Criteria andPronumBetween(String value1, String value2) {
            addCriterion("pronum between", value1, value2, "pronum");
            return (Criteria) this;
        }

        public Criteria andPronumNotBetween(String value1, String value2) {
            addCriterion("pronum not between", value1, value2, "pronum");
            return (Criteria) this;
        }

        public Criteria andProstatusIsNull() {
            addCriterion("prostatus is null");
            return (Criteria) this;
        }

        public Criteria andProstatusIsNotNull() {
            addCriterion("prostatus is not null");
            return (Criteria) this;
        }

        public Criteria andProstatusEqualTo(Integer value) {
            addCriterion("prostatus =", value, "prostatus");
            return (Criteria) this;
        }

        public Criteria andProstatusNotEqualTo(Integer value) {
            addCriterion("prostatus <>", value, "prostatus");
            return (Criteria) this;
        }

        public Criteria andProstatusGreaterThan(Integer value) {
            addCriterion("prostatus >", value, "prostatus");
            return (Criteria) this;
        }

        public Criteria andProstatusGreaterThanOrEqualTo(Integer value) {
            addCriterion("prostatus >=", value, "prostatus");
            return (Criteria) this;
        }

        public Criteria andProstatusLessThan(Integer value) {
            addCriterion("prostatus <", value, "prostatus");
            return (Criteria) this;
        }

        public Criteria andProstatusLessThanOrEqualTo(Integer value) {
            addCriterion("prostatus <=", value, "prostatus");
            return (Criteria) this;
        }

        public Criteria andProstatusIn(List<Integer> values) {
            addCriterion("prostatus in", values, "prostatus");
            return (Criteria) this;
        }

        public Criteria andProstatusNotIn(List<Integer> values) {
            addCriterion("prostatus not in", values, "prostatus");
            return (Criteria) this;
        }

        public Criteria andProstatusBetween(Integer value1, Integer value2) {
            addCriterion("prostatus between", value1, value2, "prostatus");
            return (Criteria) this;
        }

        public Criteria andProstatusNotBetween(Integer value1, Integer value2) {
            addCriterion("prostatus not between", value1, value2, "prostatus");
            return (Criteria) this;
        }

        public Criteria andProcreatetimeIsNull() {
            addCriterion("procreatetime is null");
            return (Criteria) this;
        }

        public Criteria andProcreatetimeIsNotNull() {
            addCriterion("procreatetime is not null");
            return (Criteria) this;
        }

        public Criteria andProcreatetimeEqualTo(String value) {
            addCriterion("procreatetime =", value, "procreatetime");
            return (Criteria) this;
        }

        public Criteria andProcreatetimeNotEqualTo(String value) {
            addCriterion("procreatetime <>", value, "procreatetime");
            return (Criteria) this;
        }

        public Criteria andProcreatetimeGreaterThan(String value) {
            addCriterion("procreatetime >", value, "procreatetime");
            return (Criteria) this;
        }

        public Criteria andProcreatetimeGreaterThanOrEqualTo(String value) {
            addCriterion("procreatetime >=", value, "procreatetime");
            return (Criteria) this;
        }

        public Criteria andProcreatetimeLessThan(String value) {
            addCriterion("procreatetime <", value, "procreatetime");
            return (Criteria) this;
        }

        public Criteria andProcreatetimeLessThanOrEqualTo(String value) {
            addCriterion("procreatetime <=", value, "procreatetime");
            return (Criteria) this;
        }

        public Criteria andProcreatetimeLike(String value) {
            addCriterion("procreatetime like", value, "procreatetime");
            return (Criteria) this;
        }

        public Criteria andProcreatetimeNotLike(String value) {
            addCriterion("procreatetime not like", value, "procreatetime");
            return (Criteria) this;
        }

        public Criteria andProcreatetimeIn(List<String> values) {
            addCriterion("procreatetime in", values, "procreatetime");
            return (Criteria) this;
        }

        public Criteria andProcreatetimeNotIn(List<String> values) {
            addCriterion("procreatetime not in", values, "procreatetime");
            return (Criteria) this;
        }

        public Criteria andProcreatetimeBetween(String value1, String value2) {
            addCriterion("procreatetime between", value1, value2, "procreatetime");
            return (Criteria) this;
        }

        public Criteria andProcreatetimeNotBetween(String value1, String value2) {
            addCriterion("procreatetime not between", value1, value2, "procreatetime");
            return (Criteria) this;
        }

        public Criteria andProunitIsNull() {
            addCriterion("prounit is null");
            return (Criteria) this;
        }

        public Criteria andProunitIsNotNull() {
            addCriterion("prounit is not null");
            return (Criteria) this;
        }

        public Criteria andProunitEqualTo(String value) {
            addCriterion("prounit =", value, "prounit");
            return (Criteria) this;
        }

        public Criteria andProunitNotEqualTo(String value) {
            addCriterion("prounit <>", value, "prounit");
            return (Criteria) this;
        }

        public Criteria andProunitGreaterThan(String value) {
            addCriterion("prounit >", value, "prounit");
            return (Criteria) this;
        }

        public Criteria andProunitGreaterThanOrEqualTo(String value) {
            addCriterion("prounit >=", value, "prounit");
            return (Criteria) this;
        }

        public Criteria andProunitLessThan(String value) {
            addCriterion("prounit <", value, "prounit");
            return (Criteria) this;
        }

        public Criteria andProunitLessThanOrEqualTo(String value) {
            addCriterion("prounit <=", value, "prounit");
            return (Criteria) this;
        }

        public Criteria andProunitLike(String value) {
            addCriterion("prounit like", value, "prounit");
            return (Criteria) this;
        }

        public Criteria andProunitNotLike(String value) {
            addCriterion("prounit not like", value, "prounit");
            return (Criteria) this;
        }

        public Criteria andProunitIn(List<String> values) {
            addCriterion("prounit in", values, "prounit");
            return (Criteria) this;
        }

        public Criteria andProunitNotIn(List<String> values) {
            addCriterion("prounit not in", values, "prounit");
            return (Criteria) this;
        }

        public Criteria andProunitBetween(String value1, String value2) {
            addCriterion("prounit between", value1, value2, "prounit");
            return (Criteria) this;
        }

        public Criteria andProunitNotBetween(String value1, String value2) {
            addCriterion("prounit not between", value1, value2, "prounit");
            return (Criteria) this;
        }

        public Criteria andCategoryIdIsNull() {
            addCriterion("category_id is null");
            return (Criteria) this;
        }

        public Criteria andCategoryIdIsNotNull() {
            addCriterion("category_id is not null");
            return (Criteria) this;
        }

        public Criteria andCategoryIdEqualTo(Integer value) {
            addCriterion("category_id =", value, "categoryId");
            return (Criteria) this;
        }

        public Criteria andCategoryIdNotEqualTo(Integer value) {
            addCriterion("category_id <>", value, "categoryId");
            return (Criteria) this;
        }

        public Criteria andCategoryIdGreaterThan(Integer value) {
            addCriterion("category_id >", value, "categoryId");
            return (Criteria) this;
        }

        public Criteria andCategoryIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("category_id >=", value, "categoryId");
            return (Criteria) this;
        }

        public Criteria andCategoryIdLessThan(Integer value) {
            addCriterion("category_id <", value, "categoryId");
            return (Criteria) this;
        }

        public Criteria andCategoryIdLessThanOrEqualTo(Integer value) {
            addCriterion("category_id <=", value, "categoryId");
            return (Criteria) this;
        }

        public Criteria andCategoryIdIn(List<Integer> values) {
            addCriterion("category_id in", values, "categoryId");
            return (Criteria) this;
        }

        public Criteria andCategoryIdNotIn(List<Integer> values) {
            addCriterion("category_id not in", values, "categoryId");
            return (Criteria) this;
        }

        public Criteria andCategoryIdBetween(Integer value1, Integer value2) {
            addCriterion("category_id between", value1, value2, "categoryId");
            return (Criteria) this;
        }

        public Criteria andCategoryIdNotBetween(Integer value1, Integer value2) {
            addCriterion("category_id not between", value1, value2, "categoryId");
            return (Criteria) this;
        }

        public Criteria andDiscriptionIsNull() {
            addCriterion("discription is null");
            return (Criteria) this;
        }

        public Criteria andDiscriptionIsNotNull() {
            addCriterion("discription is not null");
            return (Criteria) this;
        }

        public Criteria andDiscriptionEqualTo(String value) {
            addCriterion("discription =", value, "discription");
            return (Criteria) this;
        }

        public Criteria andDiscriptionNotEqualTo(String value) {
            addCriterion("discription <>", value, "discription");
            return (Criteria) this;
        }

        public Criteria andDiscriptionGreaterThan(String value) {
            addCriterion("discription >", value, "discription");
            return (Criteria) this;
        }

        public Criteria andDiscriptionGreaterThanOrEqualTo(String value) {
            addCriterion("discription >=", value, "discription");
            return (Criteria) this;
        }

        public Criteria andDiscriptionLessThan(String value) {
            addCriterion("discription <", value, "discription");
            return (Criteria) this;
        }

        public Criteria andDiscriptionLessThanOrEqualTo(String value) {
            addCriterion("discription <=", value, "discription");
            return (Criteria) this;
        }

        public Criteria andDiscriptionLike(String value) {
            addCriterion("discription like", value, "discription");
            return (Criteria) this;
        }

        public Criteria andDiscriptionNotLike(String value) {
            addCriterion("discription not like", value, "discription");
            return (Criteria) this;
        }

        public Criteria andDiscriptionIn(List<String> values) {
            addCriterion("discription in", values, "discription");
            return (Criteria) this;
        }

        public Criteria andDiscriptionNotIn(List<String> values) {
            addCriterion("discription not in", values, "discription");
            return (Criteria) this;
        }

        public Criteria andDiscriptionBetween(String value1, String value2) {
            addCriterion("discription between", value1, value2, "discription");
            return (Criteria) this;
        }

        public Criteria andDiscriptionNotBetween(String value1, String value2) {
            addCriterion("discription not between", value1, value2, "discription");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table product
     *
     * @mbg.generated do_not_delete_during_merge Thu Jan 07 02:14:27 CST 2021
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table product
     *
     * @mbg.generated Thu Jan 07 02:14:27 CST 2021
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}