package com.kakarote.crm9.erp.admin.dao;

import com.kakarote.crm9.erp.admin.model.WjAdminUser;
import com.kakarote.crm9.erp.admin.model.WjAdminUserExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

/**
 * 员工表
 */
public interface WjAdminUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wj_admin_user
     *
     * @mbg.generated Fri Jan 08 00:36:33 CST 2021
     */
    long countByExample(WjAdminUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wj_admin_user
     *
     * @mbg.generated Fri Jan 08 00:36:33 CST 2021
     */
    int deleteByExample(WjAdminUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wj_admin_user
     *
     * @mbg.generated Fri Jan 08 00:36:33 CST 2021
     */
    int deleteByPrimaryKey(Integer userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wj_admin_user
     *
     * @mbg.generated Fri Jan 08 00:36:33 CST 2021
     */
    int insert(WjAdminUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wj_admin_user
     *
     * @mbg.generated Fri Jan 08 00:36:33 CST 2021
     */
    int insertSelective(WjAdminUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wj_admin_user
     *
     * @mbg.generated Fri Jan 08 00:36:33 CST 2021
     */
    List<WjAdminUser> selectByExample(WjAdminUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wj_admin_user
     *
     * @mbg.generated Fri Jan 08 00:36:33 CST 2021
     */
    WjAdminUser selectByPrimaryKey(Integer userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wj_admin_user
     *
     * @mbg.generated Fri Jan 08 00:36:33 CST 2021
     */
    int updateByExampleSelective(@Param("record") WjAdminUser record, @Param("example") WjAdminUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wj_admin_user
     *
     * @mbg.generated Fri Jan 08 00:36:33 CST 2021
     */
    int updateByExample(@Param("record") WjAdminUser record, @Param("example") WjAdminUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wj_admin_user
     *
     * @mbg.generated Fri Jan 08 00:36:33 CST 2021
     */
    int updateByPrimaryKeySelective(WjAdminUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wj_admin_user
     *
     * @mbg.generated Fri Jan 08 00:36:33 CST 2021
     */
    int updateByPrimaryKey(WjAdminUser record);
    
    WjAdminUser selectByLoginUser(WjAdminUser user);
}