package com.kakarote.crm9.erp.admin.dao;

import com.kakarote.crm9.erp.admin.model.WjAdminDept;
import com.kakarote.crm9.erp.admin.model.WjAdminDeptExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface WjAdminDeptMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wj_admin_dept
     *
     * @mbg.generated Wed Jan 06 23:34:29 CST 2021
     */
    long countByExample(WjAdminDeptExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wj_admin_dept
     *
     * @mbg.generated Wed Jan 06 23:34:29 CST 2021
     */
    int deleteByExample(WjAdminDeptExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wj_admin_dept
     *
     * @mbg.generated Wed Jan 06 23:34:29 CST 2021
     */
    int deleteByPrimaryKey(Integer deptId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wj_admin_dept
     *
     * @mbg.generated Wed Jan 06 23:34:29 CST 2021
     */
    int insert(WjAdminDept record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wj_admin_dept
     *
     * @mbg.generated Wed Jan 06 23:34:29 CST 2021
     */
    int insertSelective(WjAdminDept record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wj_admin_dept
     *
     * @mbg.generated Wed Jan 06 23:34:29 CST 2021
     */
    List<WjAdminDept> selectByExample(WjAdminDeptExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wj_admin_dept
     *
     * @mbg.generated Wed Jan 06 23:34:29 CST 2021
     */
    WjAdminDept selectByPrimaryKey(Integer deptId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wj_admin_dept
     *
     * @mbg.generated Wed Jan 06 23:34:29 CST 2021
     */
    int updateByExampleSelective(@Param("record") WjAdminDept record, @Param("example") WjAdminDeptExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wj_admin_dept
     *
     * @mbg.generated Wed Jan 06 23:34:29 CST 2021
     */
    int updateByExample(@Param("record") WjAdminDept record, @Param("example") WjAdminDeptExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wj_admin_dept
     *
     * @mbg.generated Wed Jan 06 23:34:29 CST 2021
     */
    int updateByPrimaryKeySelective(WjAdminDept record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wj_admin_dept
     *
     * @mbg.generated Wed Jan 06 23:34:29 CST 2021
     */
    int updateByPrimaryKey(WjAdminDept record);
}