package com.kakarote.crm9.erp.backlog.dao;

import java.util.List;

import com.kakarote.crm9.erp.backlog.model.ClientExample;
import org.apache.ibatis.annotations.Param;
import com.kakarote.crm9.erp.backlog.model.Client;
import com.kakarote.crm9.erp.backlog.model.ClientExample;

public interface ClientMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table client
     *
     * @mbg.generated Wed Jan 06 15:32:23 CST 2021
     */
    long countByExample(ClientExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table client
     *
     * @mbg.generated Wed Jan 06 15:32:23 CST 2021
     */
    int deleteByExample(ClientExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table client
     *
     * @mbg.generated Wed Jan 06 15:32:23 CST 2021
     */
    int deleteByPrimaryKey(Integer cid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table client
     *
     * @mbg.generated Wed Jan 06 15:32:23 CST 2021
     */
    int insert(Client record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table client
     *
     * @mbg.generated Wed Jan 06 15:32:23 CST 2021
     */
    int insertSelective(Client record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table client
     *
     * @mbg.generated Wed Jan 06 15:32:23 CST 2021
     */
    List<Client> selectByExample(ClientExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table client
     *
     * @mbg.generated Wed Jan 06 15:32:23 CST 2021
     */
    Client selectByPrimaryKey(Integer cid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table client
     *
     * @mbg.generated Wed Jan 06 15:32:23 CST 2021
     */
    int updateByExampleSelective(@Param("record") Client record, @Param("example") ClientExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table client
     *
     * @mbg.generated Wed Jan 06 15:32:23 CST 2021
     */
    int updateByExample(@Param("record") Client record, @Param("example") ClientExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table client
     *
     * @mbg.generated Wed Jan 06 15:32:23 CST 2021
     */
    int updateByPrimaryKeySelective(Client record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table client
     *
     * @mbg.generated Wed Jan 06 15:32:23 CST 2021
     */
    int updateByPrimaryKey(Client record);
}