package com.kakarote.crm9.erp.abusniess.model;

public class BusinessType {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column business_type.tid
     *
     * @mbg.generated Fri Jan 08 15:32:24 CST 2021
     */
    private Integer tid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column business_type.name
     *
     * @mbg.generated Fri Jan 08 15:32:24 CST 2021
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column business_type.cjid
     *
     * @mbg.generated Fri Jan 08 15:32:24 CST 2021
     */
    private Integer cjid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column business_type.create_time
     *
     * @mbg.generated Fri Jan 08 15:32:24 CST 2021
     */
    private String createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column business_type.update_time
     *
     * @mbg.generated Fri Jan 08 15:32:24 CST 2021
     */
    private String updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column business_type.tid
     *
     * @return the value of business_type.tid
     *
     * @mbg.generated Fri Jan 08 15:32:24 CST 2021
     */
    public Integer getTid() {
        return tid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column business_type.tid
     *
     * @param tid the value for business_type.tid
     *
     * @mbg.generated Fri Jan 08 15:32:24 CST 2021
     */
    public void setTid(Integer tid) {
        this.tid = tid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column business_type.name
     *
     * @return the value of business_type.name
     *
     * @mbg.generated Fri Jan 08 15:32:24 CST 2021
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column business_type.name
     *
     * @param name the value for business_type.name
     *
     * @mbg.generated Fri Jan 08 15:32:24 CST 2021
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column business_type.cjid
     *
     * @return the value of business_type.cjid
     *
     * @mbg.generated Fri Jan 08 15:32:24 CST 2021
     */
    public Integer getCjid() {
        return cjid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column business_type.cjid
     *
     * @param cjid the value for business_type.cjid
     *
     * @mbg.generated Fri Jan 08 15:32:24 CST 2021
     */
    public void setCjid(Integer cjid) {
        this.cjid = cjid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column business_type.create_time
     *
     * @return the value of business_type.create_time
     *
     * @mbg.generated Fri Jan 08 15:32:24 CST 2021
     */
    public String getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column business_type.create_time
     *
     * @param createTime the value for business_type.create_time
     *
     * @mbg.generated Fri Jan 08 15:32:24 CST 2021
     */
    public void setCreateTime(String createTime) {
        this.createTime = createTime == null ? null : createTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column business_type.update_time
     *
     * @return the value of business_type.update_time
     *
     * @mbg.generated Fri Jan 08 15:32:24 CST 2021
     */
    public String getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column business_type.update_time
     *
     * @param updateTime the value for business_type.update_time
     *
     * @mbg.generated Fri Jan 08 15:32:24 CST 2021
     */
    public void setUpdateTime(String updateTime) {
        this.updateTime = updateTime == null ? null : updateTime.trim();
    }
}