package com.kakarote.crm9.erp.abusniess.model;

public class BusinessStatus {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column business_status.sid
     *
     * @mbg.generated Fri Jan 08 15:32:24 CST 2021
     */
    private Integer sid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column business_status.tid
     *
     * @mbg.generated Fri Jan 08 15:32:24 CST 2021
     */
    private Integer tid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column business_status.name
     *
     * @mbg.generated Fri Jan 08 15:32:24 CST 2021
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column business_status.rate
     *
     * @mbg.generated Fri Jan 08 15:32:24 CST 2021
     */
    private String rate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column business_status.order_num
     *
     * @mbg.generated Fri Jan 08 15:32:24 CST 2021
     */
    private Integer orderNum;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column business_status.sid
     *
     * @return the value of business_status.sid
     *
     * @mbg.generated Fri Jan 08 15:32:24 CST 2021
     */
    public Integer getSid() {
        return sid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column business_status.sid
     *
     * @param sid the value for business_status.sid
     *
     * @mbg.generated Fri Jan 08 15:32:24 CST 2021
     */
    public void setSid(Integer sid) {
        this.sid = sid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column business_status.tid
     *
     * @return the value of business_status.tid
     *
     * @mbg.generated Fri Jan 08 15:32:24 CST 2021
     */
    public Integer getTid() {
        return tid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column business_status.tid
     *
     * @param tid the value for business_status.tid
     *
     * @mbg.generated Fri Jan 08 15:32:24 CST 2021
     */
    public void setTid(Integer tid) {
        this.tid = tid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column business_status.name
     *
     * @return the value of business_status.name
     *
     * @mbg.generated Fri Jan 08 15:32:24 CST 2021
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column business_status.name
     *
     * @param name the value for business_status.name
     *
     * @mbg.generated Fri Jan 08 15:32:24 CST 2021
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column business_status.rate
     *
     * @return the value of business_status.rate
     *
     * @mbg.generated Fri Jan 08 15:32:24 CST 2021
     */
    public String getRate() {
        return rate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column business_status.rate
     *
     * @param rate the value for business_status.rate
     *
     * @mbg.generated Fri Jan 08 15:32:24 CST 2021
     */
    public void setRate(String rate) {
        this.rate = rate == null ? null : rate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column business_status.order_num
     *
     * @return the value of business_status.order_num
     *
     * @mbg.generated Fri Jan 08 15:32:24 CST 2021
     */
    public Integer getOrderNum() {
        return orderNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column business_status.order_num
     *
     * @param orderNum the value for business_status.order_num
     *
     * @mbg.generated Fri Jan 08 15:32:24 CST 2021
     */
    public void setOrderNum(Integer orderNum) {
        this.orderNum = orderNum;
    }
}